"use client";

import { useState, useEffect, useMemo, useRef } from "react";
import { useRouter, useParams, useSearchParams } from "next/navigation";
import { findLessonById } from "@/lib/lesson-utils";
import type { Language } from "@/lib/translations";
import { useAuthGuard } from "@/lib/auth";
import { getPlan, saveMaterials } from "@/lib/plan-storage";
import { emojiForImageDesc } from "@/lib/image-desc-emoji";

function getLang(): Language {
  if (typeof window === "undefined") return "mr";
  return (localStorage.getItem("lang") as Language) ?? "mr";
}

interface WorksheetItem {
  type: string;
  instruction_local: string;
  instruction_en: string;
  content: any;
}

function MatchPairs({ pairs }: { pairs: { word: string; image_desc: string }[] }) {
  const shuffled = useMemo(
    () => [...pairs].sort((a, b) => a.image_desc.localeCompare(b.image_desc)),
    [pairs]
  );
  return (
    <div className="grid grid-cols-2 gap-3 mt-3">
      <div className="space-y-3">
        {pairs.map((p, i) => (
          <div key={i} className="border border-[#D0EAE4] rounded-lg px-4 py-3 text-center">
            <p className="text-lg font-semibold text-primary-700">{p.word}</p>
          </div>
        ))}
      </div>
      <div className="space-y-3">
        {shuffled.map((p, i) => (
          <div key={i} className="border border-[#D0EAE4] rounded-lg px-4 py-3 text-center bg-white">
            <span className="text-4xl block">{emojiForImageDesc(p.image_desc, p.word)}</span>
            <p className="text-[10px] text-primary-300 mt-1 capitalize">{p.word}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function WorksheetPage() {
  const router = useRouter();
  useAuthGuard();
  const params = useParams();
  const searchParams = useSearchParams();
  const lessonId = params.id as string;
  const day = parseInt(searchParams.get("day") || "1");
  const lesson = findLessonById(lessonId);
  const printRef = useRef<HTMLDivElement>(null);

  const [lang, setLang] = useState<Language>("mr");
  const [items, setItems] = useState<WorksheetItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [showShareMenu, setShowShareMenu] = useState(false);

  useEffect(() => {
    setLang(getLang());
    const saved = getPlan(lessonId, day);
    if (saved.materials?.worksheet?.length) {
      setItems(saved.materials.worksheet);
      setLoading(false);
      return;
    }
    generateWorksheet();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const generateWorksheet = async () => {
    setLoading(true);
    setError("");
    try {
      const saved = getPlan(lessonId, day);
      const vocabularyFocus: string[] = saved.richPlan?.vocabulary_focus || [];
      const res = await fetch("/api/worksheet", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          lessonId,
          day,
          teacherProfile: {
            language: localStorage.getItem("lang") || "mr",
            medium: localStorage.getItem("medium") || "Marathi",
          },
          vocabularyFocus,
        }),
      });
      if (!res.ok) {
        setError("Could not generate worksheet. Please try again.");
      } else {
        const data = await res.json();
        if (data.error) {
          setError(data.error);
        } else {
          setItems(data.items || []);
          if (data.items?.length) saveMaterials(lessonId, day, "worksheet", data.items);
        }
      }
    } catch {
      setError("Could not generate worksheet. Please try again.");
    }
    setLoading(false);
  };

  const downloadPDF = () => {
    window.print();
  };

  const shareToWhatsApp = () => {
    if (!lesson) return;
    const text =
      "*PedaStudio Worksheet*\n" +
      "*" + lesson.id + " " + lesson.en + "* \u2022 Day " + day + "\n\n" +
      items.map((item, i) =>
        "*" + (i + 1) + ". " + item.instruction_en + "*\n" +
        (item.content?.words ? "   Words: " + item.content.words.join(", ") + "\n" : "") +
        (item.content?.pairs ? "   " + item.content.pairs.map((p: any) => p.word + " \u2192 " + p.image_desc).join("\n   ") + "\n" : "") +
        (item.content?.questions ? item.content.questions.map((q: any) => "   [" + q.image_desc + "] " + q.options.join(" / ")).join("\n") + "\n" : "") +
        (item.content?.sentences ? "   " + item.content.sentences.join("\n   ") + "\n" : "") +
        (item.content?.items ? "   " + item.content.items.map((it: any) => "[" + it.image_desc + "] ___").join("\n   ") + "\n" : "") +
        (item.content?.prompt ? "   " + item.content.prompt + "\n" : "") +
        (item.content?.categories ? "   Categories: " + item.content.categories.join(", ") + "\n   Words: " + (item.content.words || []).join(", ") + "\n" : "")
      ).join("\n") +
      "\n_Generated by PedaStudio_";

    const encoded = encodeURIComponent(text);
    window.open("https://wa.me/?text=" + encoded, "_blank");
  };

  const renderItem = (item: WorksheetItem, index: number) => {
    return (
      <div key={index} className="bg-white rounded-xl border border-[#D0EAE4] p-5 print:border print:border-gray-300 print:rounded-none print:p-4 print:break-inside-avoid">
        <div className="flex items-start gap-3 mb-3">
          <span className="w-8 h-8 rounded-full bg-white border-b border-[#D0EAE4] text-primary-800 flex items-center justify-center text-sm font-bold shrink-0 print:bg-gray-800">{index + 1}</span>
          <div>
            <p className="text-base font-semibold text-primary-800">{item.instruction_local}</p>
            <p className="text-sm text-primary-300 italic">{item.instruction_en}</p>
          </div>
        </div>

        {item.type === "trace" && item.content?.words && (
          <div className="flex flex-wrap gap-4 mt-3">
            {item.content.words.map((word: string, i: number) => (
              <div key={i} className="border-2 border-dashed border-slate-300 rounded-lg px-6 py-4 text-center">
                <p className="text-3xl font-bold text-slate-200 tracking-[0.3em]">{word}</p>
                <div className="mt-2 border-b-2 border-dotted border-slate-300 w-full"></div>
              </div>
            ))}
          </div>
        )}

        {item.type === "match" && item.content?.pairs && (
          <MatchPairs pairs={item.content.pairs} />
        )}

        {item.type === "circle" && item.content?.questions && (
          <div className="space-y-4 mt-3">
            {item.content.questions.map((q: any, i: number) => (
              <div key={i}>
                <span className="text-4xl block mb-2">{emojiForImageDesc(q.image_desc || "", q.answer)}</span>
                <div className="flex gap-3 flex-wrap">
                  {q.options.map((opt: string, j: number) => (
                    <span key={j} className="px-4 py-2 border-2 border-[#D0EAE4] rounded-full text-base font-semibold text-primary-700">{opt}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}

        {item.type === "fill_blank" && item.content?.sentences && (
          <div className="space-y-3 mt-3">
            {item.content.sentences.map((s: string, i: number) => (
              <p key={i} className="text-lg text-primary-700 border-b border-dotted border-slate-300 pb-2">{s}</p>
            ))}
          </div>
        )}

        {item.type === "label" && item.content?.items && (
          <div className="grid grid-cols-2 gap-4 mt-3">
            {item.content.items.map((it: any, i: number) => (
              <div key={i} className="border border-[#D0EAE4] rounded-lg p-4 text-center">
                <span className="text-4xl block mb-3">{emojiForImageDesc(it.image_desc || "", it.answer)}</span>
                <div className="border-b-2 border-dotted border-slate-300 w-3/4 mx-auto"></div>
              </div>
            ))}
          </div>
        )}

        {item.type === "draw" && item.content && (
          <div className="border-2 border-dashed border-[#D0EAE4] rounded-lg p-6 mt-3 min-h-[120px] flex items-center justify-center">
            <p className="text-sm text-primary-300">{item.content.prompt || "Draw here"}</p>
          </div>
        )}

        {item.type === "categorize" && item.content && (
          <div className="mt-3">
            <div className="flex flex-wrap gap-2 mb-3">
              {item.content.words?.map((w: string, i: number) => (
                <span key={i} className="px-3 py-1.5 bg-accent-50 rounded-lg text-base font-semibold text-primary-700">{w}</span>
              ))}
            </div>
            <div className="grid grid-cols-2 gap-3">
              {item.content.categories?.map((cat: string, i: number) => (
                <div key={i} className="border border-[#D0EAE4] rounded-lg p-3">
                  <p className="text-sm font-bold text-primary-500 mb-2">{cat}</p>
                  <div className="space-y-2">
                    <div className="border-b border-dotted border-slate-300 h-6"></div>
                    <div className="border-b border-dotted border-slate-300 h-6"></div>
                    <div className="border-b border-dotted border-slate-300 h-6"></div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

  if (!lesson) {
    return (
      <main className="min-h-screen bg-white flex flex-col items-center justify-center px-6">
        <p className="text-primary-300 mb-4">Lesson not found.</p>
        <button onClick={() => router.push("/home")} className="px-6 py-3 rounded-xl bg-accent-700 text-white font-semibold">Go Home</button>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-white">
      <style jsx global>{`
        @media print {
          body * { visibility: hidden; }
          #print-area, #print-area * { visibility: visible; }
          #print-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            padding: 20mm;
          }
          .no-print { display: none !important; }
        }
      `}</style>

      <header className="bg-white border-b border-[#D0EAE4] text-primary-800 px-5 py-4 no-print">
        <div className="flex items-center gap-3">
          <button onClick={() => router.back()} className="text-primary-400 hover:text-primary-600">{"\u2190"}</button>
          <div className="flex-1">
            <p className="text-base font-semibold">{lesson.id} {lesson.en}</p>
            <p className="text-xs text-primary-300">Worksheet {"\u2022"} Day {day}</p>
          </div>
        </div>
      </header>

      <div className="no-print px-5 py-3 space-y-2">
        <div className="flex gap-3">
          <button onClick={downloadPDF} className="flex-1 py-3 rounded-xl bg-white border-b border-[#D0EAE4] text-primary-800 font-semibold text-sm flex items-center justify-center gap-2">
            {"\uD83D\uDCC4"} Save as PDF
          </button>
          <button onClick={shareToWhatsApp} className="flex-1 py-3 rounded-xl bg-[#25D366] text-white font-semibold text-sm flex items-center justify-center gap-2">
            {"\uD83D\uDCE4"} WhatsApp
          </button>
        </div>
        <button onClick={generateWorksheet} disabled={loading} className="w-full py-3 rounded-xl border border-[#D0EAE4] text-primary-600 font-semibold text-sm disabled:opacity-50">
          {"\uD83D\uDD04"} Regenerate
        </button>
      </div>

      <div id="print-area" ref={printRef} className="px-5 pb-8">
        <div className="hidden print:block mb-6 text-center border-b-2 border-black pb-4">
          <p className="text-xl font-bold">PedaStudio Worksheet</p>
          <p className="text-base mt-1">{lesson.id} {lesson.en} {"\u2022"} Day {day}</p>
          <p className="text-sm text-gray-600 mt-1">{lesson[lang]}</p>
          <div className="flex justify-between mt-3 text-sm">
            <span>Name: ___________________________</span>
            <span>Date: ________________</span>
          </div>
        </div>

        {loading && (
          <div className="text-center py-20">
            <div className="inline-flex gap-1.5">
              <span className="w-3 h-3 bg-primary-500 rounded-full animate-bounce"></span>
              <span className="w-3 h-3 bg-primary-500 rounded-full animate-bounce" style={{animationDelay: "150ms"}}></span>
              <span className="w-3 h-3 bg-primary-500 rounded-full animate-bounce" style={{animationDelay: "300ms"}}></span>
            </div>
            <p className="text-sm text-primary-300 mt-4">Generating worksheet...</p>
          </div>
        )}

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-center">
            <p className="text-red-600 text-sm">{error}</p>
            <button onClick={generateWorksheet} className="mt-3 px-4 py-2 bg-red-600 text-white rounded-lg text-sm font-semibold">Try Again</button>
          </div>
        )}

        {!loading && !error && items.length > 0 && (
          <div className="space-y-4">
            {items.map((item, i) => renderItem(item, i))}
          </div>
        )}

        {!loading && !error && items.length === 0 && (
          <div className="text-center py-20">
            <p className="text-primary-300">No worksheet items generated.</p>
            <button onClick={generateWorksheet} className="mt-3 px-6 py-3 bg-white border-b border-[#D0EAE4] text-primary-800 rounded-xl font-semibold">Generate</button>
          </div>
        )}

        <div className="hidden print:block mt-8 text-center border-t border-gray-300 pt-3">
          <p className="text-xs text-gray-400">Generated by PedaStudio {"\u2022"} Balbharati Grade 1 English 2025-26</p>
        </div>
      </div>
    </main>
  );
}