// Grade 3 English (L2) — Non-English Medium Schools
// Balbharati 2025-26 — "My English Book Three"
// 6 units with varied sub-lessons

export const grade3EnglishL2Lessons = [
  // Unit 1
  { id: "3-1.1", en: "Play Time", unit: 1, pages: "1-2", days: 2, type: "song" as const,
    vocabulary: ["play", "games", "run", "jump", "catch", "throw", "kick", "swing", "slide", "hide"],
    structures: ["Let's play ___.", "I like to ___."],
    competencies: ["Sings/recites with actions", "Names games and play activities"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn song, play vocabulary" }, { day: 2, level: "Apply", focus: "Describe favourite games, act out" }] },
  { id: "3-1.2", en: "Revision - Letters & Words", unit: 1, pages: "3-4", days: 2, type: "phonics" as const,
    vocabulary: ["letters", "words", "sounds", "match", "read", "write"],
    structures: ["The letter ___ makes the sound ___."],
    competencies: ["Recognises letters and sounds", "Reads simple words"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Revise letter sounds and CVC words" }, { day: 2, level: "Apply", focus: "Read words, match to pictures" }] },
  { id: "3-1.3", en: "A Guessing Game", unit: 1, pages: "5-6", days: 2, type: "conversation" as const,
    vocabulary: ["guess", "clues", "think", "answer", "describe", "riddle"],
    structures: ["It is ___. It has ___. What is it?"],
    competencies: ["Describes objects using clues", "Guesses from descriptions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Play guessing game with picture clues" }, { day: 2, level: "Apply", focus: "Create own riddles, describe objects" }] },
  { id: "3-1.4", en: "Spot the Letter", unit: 1, pages: "7-8", days: 2, type: "phonics" as const,
    vocabulary: ["spot", "find", "letter", "word", "beginning", "ending"],
    structures: ["This word starts with ___.", "Find the letter ___."],
    competencies: ["Identifies letters in words", "Sorts by beginning sounds"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Spot letters b, c, f, p, t in words" }, { day: 2, level: "Apply", focus: "Sort words by starting letter" }] },
  { id: "3-1.5", en: "Priya in the Village / Riya in the City", unit: 1, pages: "9-14", days: 3, type: "story" as const,
    vocabulary: ["village", "city", "farm", "building", "market", "garden", "pond", "road", "bus", "auto", "tractor"],
    structures: ["In the village, there is ___.", "In the city, we can see ___."],
    competencies: ["Compares village and city life", "Reads passages with comprehension", "Describes places"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read about Priya's village — farm, pond, animals" }, { day: 2, level: "Understand", focus: "Read about Riya's city — buildings, traffic, shops" }, { day: 3, level: "Apply", focus: "Compare village and city, describe own area" }] },
  { id: "3-1.6", en: "More or Less", unit: 1, pages: "15-16", days: 2, type: "conversation" as const,
    vocabulary: ["more", "less", "many", "few", "how many", "count", "numbers"],
    structures: ["There are more ___ than ___.", "How many ___ are there?"],
    competencies: ["Compares quantities", "Uses more/less/many/few", "Counts objects"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn more/less with picture comparisons" }, { day: 2, level: "Apply", focus: "Count and compare objects in classroom" }] },
  { id: "3-1.7", en: "Days of the Week", unit: 1, pages: "17", days: 2, type: "song" as const,
    vocabulary: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "week", "today", "tomorrow", "yesterday"],
    structures: ["Today is ___.", "Tomorrow will be ___.", "Yesterday was ___."],
    competencies: ["Names days of the week in order", "Uses today/tomorrow/yesterday"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Sing days song, learn sequence" }, { day: 2, level: "Apply", focus: "Tell what day it is, answer day questions" }] },
  { id: "3-1.8", en: "Who are you?", unit: 1, pages: "18-19", days: 2, type: "conversation" as const,
    vocabulary: ["who", "name", "age", "school", "class", "friend", "live", "family"],
    structures: ["Who are you?", "I am ___.", "I live in ___."],
    competencies: ["Introduces self fully", "Asks and answers personal questions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn full self-introduction" }, { day: 2, level: "Apply", focus: "Interview classmates, report back" }] },
  // Unit 2
  { id: "3-2.1", en: "Can you?", unit: 2, pages: "20-21", days: 2, type: "conversation" as const,
    vocabulary: ["can", "cannot", "swim", "fly", "read", "write", "draw", "dance", "cook", "climb"],
    structures: ["Can you ___?", "Yes, I can.", "No, I can't."],
    competencies: ["Uses can/can't for abilities", "Asks about abilities"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn can/can't dialogues" }, { day: 2, level: "Apply", focus: "Survey classmates on abilities, make chart" }] },
  { id: "3-2.2", en: "Strings of Actions", unit: 2, pages: "22-23", days: 2, type: "conversation" as const,
    vocabulary: ["first", "then", "next", "after that", "finally", "wake up", "get ready", "go to school"],
    structures: ["First I ___. Then I ___.", "After that, I ___."],
    competencies: ["Uses sequence words", "Describes routines in order"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn sequence words: first, then, next" }, { day: 2, level: "Apply", focus: "Describe morning routine in sequence" }] },
  { id: "3-2.3", en: "Vowel Sounds", unit: 2, pages: "24-25", days: 2, type: "phonics" as const,
    vocabulary: ["vowel", "a", "e", "i", "o", "u", "short", "long", "sound"],
    structures: ["The vowel in ___ is ___.", "Short a sounds like ___."],
    competencies: ["Identifies vowel sounds in words", "Distinguishes short and long vowels"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Identify short vowel sounds a, e, i" }, { day: 2, level: "Apply", focus: "Identify o, u vowels, sort words by vowel" }] },
  { id: "3-2.4", en: "Apples and Bananas", unit: 2, pages: "26-27", days: 2, type: "song" as const,
    vocabulary: ["apples", "bananas", "eat", "like", "yummy", "fruit"],
    structures: ["I like to eat ___.", "Apples and bananas are ___."],
    competencies: ["Sings songs with vowel substitution", "Names fruits"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Sing Apples and Bananas song" }, { day: 2, level: "Apply", focus: "Substitute vowels to make silly words, name fruits" }] },
  { id: "3-2.5", en: "We can read and write 1", unit: 2, pages: "28-29", days: 2, type: "phonics" as const,
    vocabulary: ["read", "write", "sentence", "word", "story", "picture"],
    structures: ["I can read ___.", "I can write ___."],
    competencies: ["Reads short sentences", "Writes 3-4 word sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read simple sentences with known words" }, { day: 2, level: "Apply", focus: "Write sentences about pictures" }] },
  { id: "3-2.6", en: "Action Time", unit: 2, pages: "30", days: 1, type: "conversation" as const,
    vocabulary: ["action", "do", "act", "show", "perform"],
    structures: ["Show me how you ___.", "I am ___ing."],
    competencies: ["Performs actions from instructions", "Uses present continuous"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Act out actions, describe what you're doing" }] },
  { id: "3-2.7", en: "Let's speak", unit: 2, pages: "31", days: 2, type: "conversation" as const,
    vocabulary: ["speak", "tell", "ask", "answer", "question", "dialogue"],
    structures: ["Can you tell me ___?", "Let me tell you about ___."],
    competencies: ["Engages in dialogues", "Asks and answers questions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Practise dialogues from textbook" }, { day: 2, level: "Apply", focus: "Create own dialogues, perform in pairs" }] },
  { id: "3-2.8", en: "Consonant Blends", unit: 2, pages: "32-33", days: 2, type: "phonics" as const,
    vocabulary: ["blend", "cluster", "hr", "st", "sp", "tr", "br", "cr", "fl", "gl"],
    structures: ["___ starts with the blend ___."],
    competencies: ["Reads consonant blends", "Identifies blends in words"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn h, k, l, r, s blends" }, { day: 2, level: "Apply", focus: "Find blend words, read sentences" }] },
  { id: "3-2.9", en: "We can read and write 2", unit: 2, pages: "34-35", days: 2, type: "phonics" as const,
    vocabulary: ["paragraph", "passage", "understand", "meaning"],
    structures: ["Read and answer.", "What does ___ mean?"],
    competencies: ["Reads short passages", "Answers comprehension questions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read passage, identify key information" }, { day: 2, level: "Understand", focus: "Answer questions, find meanings" }] },
  { id: "3-2.10", en: "Please help!", unit: 2, pages: "36-37", days: 2, type: "conversation" as const,
    vocabulary: ["help", "please", "thank you", "need", "problem", "sorry"],
    structures: ["Please help me ___.", "Can you help me with ___?"],
    competencies: ["Asks for help politely", "Offers help to others"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn polite request dialogues" }, { day: 2, level: "Apply", focus: "Role-play asking for and offering help" }] },
  { id: "3-2.11", en: "We are all together", unit: 2, pages: "38-39", days: 2, type: "story" as const,
    vocabulary: ["together", "friends", "share", "help", "team", "group", "class", "school"],
    structures: ["We are all together.", "Let's work together."],
    competencies: ["Reads about teamwork", "Discusses cooperation"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story about working together" }, { day: 2, level: "Understand", focus: "Discuss importance of teamwork, share examples" }] },
  // Unit 3
  { id: "3-3.1", en: "Plant Magic", unit: 3, pages: "40-41", days: 2, type: "picture-talk" as const,
    vocabulary: ["plant", "seed", "root", "stem", "leaf", "flower", "fruit", "water", "sunlight", "soil", "grow"],
    structures: ["A plant needs ___.", "First the seed ___, then it ___."],
    competencies: ["Names parts of a plant", "Describes plant growth sequence"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn plant parts, growth sequence" }, { day: 2, level: "Apply", focus: "Draw and label plant, describe growth" }] },
  { id: "3-3.2", en: "Words and Puzzles", unit: 3, pages: "42-43", days: 2, type: "phonics" as const,
    vocabulary: ["puzzle", "crossword", "across", "down", "clue", "solve"],
    structures: ["___ across.", "___ down."],
    competencies: ["Solves word puzzles", "Spells words correctly"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn puzzle vocabulary, solve simple crossword" }, { day: 2, level: "Apply", focus: "Create own word puzzles" }] },
  { id: "3-3.3", en: "Kind Kondiba", unit: 3, pages: "44-47", days: 3, type: "story" as const,
    vocabulary: ["kind", "help", "village", "farmer", "field", "crops", "rain", "drought", "share", "generous"],
    structures: ["Kondiba helped by ___.", "He was kind because ___."],
    competencies: ["Reads stories with moral", "Narrates story events", "Understands kindness"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Listen to story, identify characters" }, { day: 2, level: "Understand", focus: "Answer questions, discuss moral" }, { day: 3, level: "Apply", focus: "Retell story, write about being kind" }] },
  // Unit 4
  { id: "3-4.1", en: "Three Little Kittens", unit: 4, pages: "48-49", days: 2, type: "poem" as const,
    vocabulary: ["kittens", "mittens", "lost", "found", "mother", "pie", "naughty", "cried", "dear"],
    structures: ["The kittens lost their ___.", "Mother said, '___.'"],
    competencies: ["Recites poems with expression", "Sequences story events in poem"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, identify characters and events" }, { day: 2, level: "Apply", focus: "Enact poem, discuss responsibility" }] },
  { id: "3-4.2", en: "Riddles", unit: 4, pages: "50-51", days: 2, type: "conversation" as const,
    vocabulary: ["riddle", "answer", "think", "guess", "clue"],
    structures: ["I have ___ but I can't ___. Who am I?"],
    competencies: ["Solves riddles", "Creates own riddles", "Thinks creatively"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Solve riddles from textbook" }, { day: 2, level: "Apply", focus: "Create own riddles about classroom objects" }] },
  { id: "3-4.3", en: "Capital Letters", unit: 4, pages: "52-55", days: 3, type: "phonics" as const,
    vocabulary: ["capital", "small", "letter", "name", "sentence", "beginning", "I"],
    structures: ["Use a capital letter for ___.", "Names begin with a capital letter."],
    competencies: ["Uses capital letters correctly", "Identifies when capitals are needed"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn rules: beginning of sentence, names, I" }, { day: 2, level: "Apply", focus: "Correct sentences with missing capitals" }, { day: 3, level: "Apply", focus: "Write sentences using capital letters correctly" }] },
  { id: "3-4.4", en: "Mix a Pancake", unit: 4, pages: "56-57", days: 2, type: "poem" as const,
    vocabulary: ["mix", "pancake", "stir", "pop", "toss", "fry", "catch", "batter", "pan"],
    structures: ["Mix a pancake, stir a pancake, ___ it in the pan."],
    competencies: ["Recites poem with actions", "Follows recipe-like instructions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem with cooking actions" }, { day: 2, level: "Apply", focus: "Describe steps of making something, sequence" }] },
  { id: "3-4.5", en: "Banana Delight", unit: 4, pages: "58-59", days: 2, type: "conversation" as const,
    vocabulary: ["banana", "recipe", "ingredients", "mix", "add", "cut", "serve", "delicious"],
    structures: ["First, ___ the ___. Then add ___."],
    competencies: ["Reads and follows recipe", "Uses sequence words"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read banana delight recipe" }, { day: 2, level: "Apply", focus: "Write steps for own simple recipe" }] },
  { id: "3-4.6", en: "Action Words", unit: 4, pages: "60-61", days: 2, type: "conversation" as const,
    vocabulary: ["run", "walk", "sit", "stand", "read", "write", "eat", "drink", "sleep", "play", "jump", "sing"],
    structures: ["___ is an action word.", "The boy is ___ing."],
    competencies: ["Identifies action words (verbs)", "Uses verbs in sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn 12 action words with charades" }, { day: 2, level: "Apply", focus: "Write sentences using action words" }] },
  { id: "3-4.7", en: "The Sun and the Wind", unit: 4, pages: "62-65", days: 3, type: "story" as const,
    vocabulary: ["sun", "wind", "strong", "blow", "shine", "traveller", "coat", "warm", "gentle", "challenge"],
    structures: ["The wind said, '___.'", "The sun said, '___.'"],
    competencies: ["Reads Aesop's fable", "Understands moral: gentleness wins"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Listen to story, identify the challenge" }, { day: 2, level: "Understand", focus: "Discuss moral, answer questions" }, { day: 3, level: "Apply", focus: "Enact story, compare wind and sun approaches" }] },
  { id: "3-4.8", en: "Weather Words", unit: 4, pages: "66-67", days: 2, type: "picture-talk" as const,
    vocabulary: ["sunny", "rainy", "cloudy", "windy", "stormy", "foggy", "hot", "cold", "warm", "cool"],
    structures: ["Today it is ___.", "When it is ___, I wear ___."],
    competencies: ["Describes weather conditions", "Associates weather with clothing"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn weather words with pictures" }, { day: 2, level: "Apply", focus: "Describe today's weather, draw weather chart" }] },
  { id: "3-4.9", en: "Mottoes", unit: 4, pages: "68", days: 1, type: "conversation" as const,
    vocabulary: ["motto", "motto", "rule", "value", "honesty", "kindness", "respect"],
    structures: ["My motto is ___.", "We should always ___."],
    competencies: ["Understands simple mottoes", "Discusses values"],
    bloomsProgression: [{ day: 1, level: "Understand", focus: "Read and discuss mottoes, connect to life" }] },
  // Unit 5
  { id: "3-5.1", en: "In the World of Letters", unit: 5, pages: "69-70", days: 2, type: "phonics" as const,
    vocabulary: ["alphabet", "order", "dictionary", "first", "last", "arrange"],
    structures: ["___ comes before ___.", "Arrange in alphabetical order."],
    competencies: ["Arranges words in alphabetical order", "Uses dictionary skills"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Practise alphabetical order with word lists" }, { day: 2, level: "Apply", focus: "Arrange classmates' names in order" }] },
  { id: "3-5.2", en: "Rahim and his Camel", unit: 5, pages: "71-73", days: 3, type: "story" as const,
    vocabulary: ["camel", "desert", "tent", "cold", "warm", "nose", "push", "space", "story"],
    structures: ["The camel said, '___.'", "Rahim allowed ___."],
    competencies: ["Reads story with dialogue", "Understands consequences", "Narrates story events"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Listen to story, identify what happens" }, { day: 2, level: "Understand", focus: "Discuss moral, answer comprehension questions" }, { day: 3, level: "Apply", focus: "Retell story, discuss setting boundaries" }] },
  { id: "3-5.3", en: "Faces and Feelings", unit: 5, pages: "74-75", days: 2, type: "conversation" as const,
    vocabulary: ["happy", "sad", "angry", "scared", "surprised", "tired", "excited", "worried", "feelings", "face"],
    structures: ["I feel ___.", "She looks ___.", "When I am ___, I ___."],
    competencies: ["Names emotions", "Describes feelings", "Reads facial expressions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn emotion words, match to face pictures" }, { day: 2, level: "Apply", focus: "Describe own feelings, role-play emotions" }] },
  { id: "3-5.4", en: "Find a friend", unit: 5, pages: "76-77", days: 2, type: "conversation" as const,
    vocabulary: ["friend", "friendly", "share", "play", "help", "kind", "together"],
    structures: ["A good friend ___.", "I found a friend who ___."],
    competencies: ["Talks about friendship", "Describes qualities of a friend"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Discuss what makes a good friend" }, { day: 2, level: "Apply", focus: "Write about best friend, share with class" }] },
  { id: "3-5.5", en: "Speak or Pass", unit: 5, pages: "78-79", days: 2, type: "conversation" as const,
    vocabulary: ["speak", "pass", "turn", "topic", "opinion", "agree", "disagree"],
    structures: ["I think ___.", "I agree/disagree because ___."],
    competencies: ["Expresses opinions", "Takes turns speaking", "Speaks confidently"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Play speak-or-pass game on simple topics" }, { day: 2, level: "Apply", focus: "Express opinions on school topics" }] },
  { id: "3-5.6", en: "A Lot of Work to Do", unit: 5, pages: "80-81", days: 2, type: "conversation" as const,
    vocabulary: ["work", "chores", "homework", "clean", "wash", "study", "help", "busy", "finished"],
    structures: ["I have to ___.", "I need to ___ before I can ___."],
    competencies: ["Describes tasks and chores", "Uses 'have to' structure"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn chore vocabulary, 'have to' structure" }, { day: 2, level: "Apply", focus: "List daily tasks, describe in sequence" }] },
  { id: "3-5.7", en: "See you later", unit: 5, pages: "82-83", days: 2, type: "conversation" as const,
    vocabulary: ["goodbye", "see you", "later", "tomorrow", "take care", "bye"],
    structures: ["See you later!", "Goodbye, see you tomorrow."],
    competencies: ["Uses farewell expressions", "Reads dialogues with intonation"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn goodbye expressions for different situations" }, { day: 2, level: "Apply", focus: "Role-play farewell situations" }] },
  // Unit 6
  { id: "3-6.1", en: "An Alphabet Song", unit: 6, pages: "84", days: 1, type: "song" as const,
    vocabulary: ["alphabet", "song", "letter", "sound", "sing"],
    structures: ["A B C D E F G..."],
    competencies: ["Sings alphabet song", "Identifies all 26 letters"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Sing alphabet song with rhythm" }] },
  { id: "3-6.2", en: "Opposites", unit: 6, pages: "85", days: 2, type: "conversation" as const,
    vocabulary: ["big", "small", "tall", "short", "hot", "cold", "fast", "slow", "old", "new", "clean", "dirty", "open", "close"],
    structures: ["The opposite of ___ is ___.", "___ and ___ are opposites."],
    competencies: ["Identifies opposite pairs", "Uses opposites in sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn 7 opposite pairs" }, { day: 2, level: "Apply", focus: "Use opposites in sentences, play matching game" }] },
  { id: "3-6.3", en: "Mary had a little lamb", unit: 6, pages: "86", days: 2, type: "poem" as const,
    vocabulary: ["Mary", "lamb", "fleece", "white", "snow", "school", "followed", "rule"],
    structures: ["Mary had a little lamb.", "It followed her to ___."],
    competencies: ["Recites classic poem", "Identifies rhyming words"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, find rhyming words" }, { day: 2, level: "Apply", focus: "Create new verse with different animal" }] },
  { id: "3-6.4", en: "Map Reading", unit: 6, pages: "87", days: 2, type: "picture-talk" as const,
    vocabulary: ["map", "north", "south", "east", "west", "near", "far", "direction", "road"],
    structures: ["___ is to the north.", "Go ___ to reach ___."],
    competencies: ["Reads simple maps", "Gives directions", "Uses position words"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn direction words, read simple map" }, { day: 2, level: "Apply", focus: "Give directions to places in school" }] },
  { id: "3-6.5", en: "Travel Manners", unit: 6, pages: "88-89", days: 2, type: "conversation" as const,
    vocabulary: ["manners", "queue", "seat", "ticket", "bus", "train", "wait", "polite", "elderly"],
    structures: ["We should ___ while travelling.", "It is good manners to ___."],
    competencies: ["Discusses travel etiquette", "Uses should/shouldn't"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn travel manners rules" }, { day: 2, level: "Apply", focus: "Discuss good manners, role-play bus journey" }] },
  { id: "3-6.6", en: "The Best Person in Town", unit: 6, pages: "90-92", days: 3, type: "story" as const,
    vocabulary: ["best", "person", "town", "help", "kind", "selfish", "generous", "everyone", "neighbours"],
    structures: ["The best person is someone who ___.", "Everyone liked ___ because ___."],
    competencies: ["Reads story about good character", "Discusses values"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Listen to story, identify the best person" }, { day: 2, level: "Understand", focus: "Discuss what makes someone the best" }, { day: 3, level: "Apply", focus: "Write about someone kind you know" }] },
  { id: "3-6.7", en: "Spelling Fun", unit: 6, pages: "93", days: 1, type: "phonics" as const,
    vocabulary: ["spelling", "correct", "wrong", "check", "practise"],
    structures: ["How do you spell ___?", "___ is spelt ___."],
    competencies: ["Spells common words correctly", "Identifies spelling errors"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Spelling bee game, correct misspelled words" }] },
  { id: "3-6.8", en: "My mobile is ringing", unit: 6, pages: "94-95", days: 2, type: "conversation" as const,
    vocabulary: ["mobile", "phone", "ring", "call", "hello", "speak", "message", "number"],
    structures: ["Hello, this is ___.", "May I speak to ___?"],
    competencies: ["Uses telephone language", "Makes polite phone conversations"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn phone conversation phrases" }, { day: 2, level: "Apply", focus: "Role-play phone calls for different purposes" }] },
  { id: "3-6.9", en: "A Lovely Bird in the Garden", unit: 6, pages: "96-97", days: 2, type: "story" as const,
    vocabulary: ["bird", "garden", "lovely", "nest", "tree", "fly", "sing", "feathers", "beautiful", "watch"],
    structures: ["There was a lovely bird in ___.", "The bird could ___."],
    competencies: ["Reads descriptive passages", "Describes birds and nature"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story, describe the bird" }, { day: 2, level: "Apply", focus: "Draw a bird, write 5 sentences about it" }] },
  { id: "3-6.10", en: "Let's speak / Matching Parts / Messages", unit: 6, pages: "98-100", days: 2, type: "conversation" as const,
    vocabulary: ["message", "match", "parts", "sentence", "complete", "speak", "write"],
    structures: ["Match ___ with ___.", "Complete the message."],
    competencies: ["Matches sentence parts", "Reads and writes short messages"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Match sentence halves, complete messages" }, { day: 2, level: "Apply", focus: "Write own short messages to friends" }] },
];

export const grade3EnglishL2AssessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  "3-A1": { name: "Unit 1: Play & Places", lessons: ["3-1.1", "3-1.2", "3-1.3", "3-1.4", "3-1.5"], focus: "Play time, letter revision, guessing games, village vs city" },
  "3-A2": { name: "Unit 1-2: Days & Abilities", lessons: ["3-1.6", "3-1.7", "3-1.8", "3-2.1", "3-2.2"], focus: "More/less, days of week, self-intro, can/can't, sequences" },
  "3-A3": { name: "Unit 2: Vowels & Reading", lessons: ["3-2.3", "3-2.4", "3-2.5", "3-2.6", "3-2.7", "3-2.8"], focus: "Vowel sounds, songs, reading, speaking, blends" },
  "3-A4": { name: "Unit 2-3: Reading & Plants", lessons: ["3-2.9", "3-2.10", "3-2.11", "3-3.1", "3-3.2"], focus: "Reading comprehension, helping, teamwork, plants, puzzles" },
  "3-A5": { name: "Unit 3-4: Stories & Poems", lessons: ["3-3.3", "3-4.1", "3-4.2", "3-4.3"], focus: "Kind Kondiba, Three Little Kittens, riddles, capitals" },
  "3-A6": { name: "Unit 4: Cooking & Weather", lessons: ["3-4.4", "3-4.5", "3-4.6", "3-4.7", "3-4.8", "3-4.9"], focus: "Pancake poem, recipes, action words, Sun & Wind, weather" },
  "3-A7": { name: "Unit 5: Letters & Feelings", lessons: ["3-5.1", "3-5.2", "3-5.3", "3-5.4", "3-5.5", "3-5.6", "3-5.7"], focus: "Alphabetical order, Rahim's Camel, emotions, friendship" },
  "3-A8": { name: "Unit 6: World Around", lessons: ["3-6.1", "3-6.2", "3-6.3", "3-6.4", "3-6.5", "3-6.6", "3-6.7", "3-6.8", "3-6.9", "3-6.10"], focus: "Alphabet song, opposites, maps, manners, phone, messages" },
};
