// Grade 2 English (L2) — Non-English Medium Schools
// Balbharati 2025-26 — "My English Book Two"
// 4 units, ~11 sub-lessons per unit = ~44 sub-lessons
// For Marathi/Hindi/Urdu/Gujarati/Kannada/etc. medium schools

export const grade2EnglishL2Lessons = [
  // UNIT 1
  { id: "2-1.1", en: "Bounce a Ball", unit: 1, pages: "1", days: 2, type: "song" as const,
    vocabulary: ["bounce", "ball", "roll", "hit", "throw", "kick", "teacher", "got", "missed"],
    structures: ["Bounce a ball to ___.", "Yes! I got it.", "Oh no! I missed it."],
    competencies: ["Recites songs with actions", "Replaces words in songs", "Follows rhythm"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing song with actions, learn action words: bounce, roll, throw, kick" },
      { day: 2, level: "Apply", focus: "Replace 'bounce' with roll/hit/throw/kick, sing new versions" }] },
  { id: "2-1.2", en: "Activity Time - Please", unit: 1, pages: "2", days: 1, type: "conversation" as const,
    vocabulary: ["please", "sit down", "stand up", "hop", "turn around", "listen"],
    structures: ["Please sit down.", "Please stand up."],
    competencies: ["Follows instructions", "Identifies 'please' as polite word", "Listens and acts"],
    bloomsProgression: [
      { day: 1, level: "Apply", focus: "Listen and act game — only follow when teacher says 'Please'" }] },
  { id: "2-1.3", en: "Let's Speak - Friends", unit: 1, pages: "3-4", days: 2, type: "conversation" as const,
    vocabulary: ["hello", "hi", "name", "friends", "water bottle", "dictionary", "useful", "lend", "thirsty"],
    structures: ["Hi, I am ___.", "We are friends.", "May I have some ___?", "Can you lend me ___?"],
    competencies: ["Introduces self", "Uses stock expressions", "Makes polite requests"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn introduction dialogues, practise in pairs" },
      { day: 2, level: "Apply", focus: "Role-play borrowing items, using 'May I' and 'Can you'" }] },
  { id: "2-1.4", en: "Let's Revise", unit: 1, pages: "5", days: 1, type: "picture-talk" as const,
    vocabulary: ["pictures", "names", "identify", "match"],
    structures: ["This is a ___.", "I can see a ___."],
    competencies: ["Names objects from pictures", "Reads familiar words at sight"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Name pictures, match words to images" }] },
  { id: "2-1.5", en: "Fun with Alphabet", unit: 1, pages: "6-8", days: 3, type: "phonics" as const,
    vocabulary: ["alphabet", "A to Z", "capital", "small", "letter", "first letter", "riddle", "mirror"],
    structures: ["A B C D...", "Write the first letter."],
    competencies: ["Recognises all 26 letters", "Writes capital and small letters", "Solves riddles"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Say and identify A-M with capital and small forms" },
      { day: 2, level: "Remember", focus: "Say and identify N-Z, match pictures to first letters" },
      { day: 3, level: "Apply", focus: "Solve riddle (mirror), write first letter of picture names" }] },
  { id: "2-1.6", en: "Activity Time - Riddles", unit: 1, pages: "8", days: 1, type: "conversation" as const,
    vocabulary: ["riddle", "guess", "look", "raise", "right", "left"],
    structures: ["Who am I?", "I look at you, you look at me."],
    competencies: ["Solves riddles", "Guesses meanings from context", "Thinks creatively"],
    bloomsProgression: [
      { day: 1, level: "Understand", focus: "Solve mirror riddle, create own simple riddles" }] },
  { id: "2-1.7", en: "Let's Speak - I want to", unit: 1, pages: "9", days: 2, type: "conversation" as const,
    vocabulary: ["want", "play", "rain", "enjoy", "go out", "wet", "finish", "join"],
    structures: ["I want to ___.", "May I go?", "Yes, you may."],
    competencies: ["Expresses personal needs", "Uses 'I want to' structure", "Asks permission"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn 'I want to' dialogues about playing in rain" },
      { day: 2, level: "Apply", focus: "Create own 'I want to' sentences, role-play" }] },
  { id: "2-1.8", en: "Word Basket - 'a' sound", unit: 1, pages: "10-11", days: 2, type: "phonics" as const,
    vocabulary: ["bat", "cat", "cap", "tap", "bag", "sat", "mat", "hat", "can", "man", "pan", "jam", "sad", "rat", "had", "fat"],
    structures: ["The fat cat sat on a mat.", "A rat has a bat."],
    competencies: ["Reads CVC words with 'a'", "Matches words to pictures", "Reads simple sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read -at, -an, -ag word families" },
      { day: 2, level: "Apply", focus: "Read short sentences with CVC words, match and read" }] },
  { id: "2-1.9", en: "Learning Letters", unit: 1, pages: "12-13", days: 2, type: "phonics" as const,
    vocabulary: ["trace", "write", "capital", "small", "letter", "match"],
    structures: ["Trace and write Aa, Bb, Cc..."],
    competencies: ["Traces and writes A-G", "Matches letters to pictures", "Develops handwriting"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Trace letters A-D, match to picture names" },
      { day: 2, level: "Apply", focus: "Trace letters E-G, write independently" }] },
  { id: "2-1.10", en: "Animal Song", unit: 1, pages: "14", days: 2, type: "song" as const,
    vocabulary: ["hen", "goat", "mouse", "chick", "cat", "bear", "kite", "sheep", "count", "coat", "house", "hat", "sleep"],
    structures: ["Hen, hen, count to ten.", "Cat, cat, find your hat."],
    competencies: ["Sings with actions", "Identifies rhyming words", "Names animals"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing animal song, learn animal names" },
      { day: 2, level: "Apply", focus: "Find rhyming pairs: ten-hen, coat-goat, hat-cat" }] },
  { id: "2-1.11", en: "Reading Time", unit: 1, pages: "15", days: 1, type: "picture-talk" as const,
    vocabulary: ["drawing", "sky", "sun", "clouds", "tree", "bird", "cow", "horse", "dancing", "sitting", "grazing", "meadow"],
    structures: ["I am drawing.", "The ___ is sitting near the ___."],
    competencies: ["Reads picture descriptions", "Identifies objects in pictures", "Reads familiar words"],
    bloomsProgression: [
      { day: 1, level: "Understand", focus: "Read picture description, identify objects, answer questions" }] },
  // UNIT 2
  { id: "2-2.1", en: "Birds can Fly", unit: 2, pages: "16", days: 2, type: "poem" as const,
    vocabulary: ["birds", "fly", "sky", "frogs", "jump", "ducks", "swim", "dogs", "walk", "horses", "run", "bunnies", "hop"],
    structures: ["Birds can fly.", "I can ___ too."],
    competencies: ["Sings/recites with actions", "Associates animals with actions", "Uses 'can' structure"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing poem, learn animal-action pairs" },
      { day: 2, level: "Apply", focus: "Create new verses with different animals, enact" }] },
  { id: "2-2.2", en: "Activity Time - Guessing Game", unit: 2, pages: "17", days: 1, type: "conversation" as const,
    vocabulary: ["guess", "think", "swims", "flies", "runs", "ball", "star", "pen", "lion", "cup", "tree", "fish"],
    structures: ["It swims in water. What is it?", "It's a ___."],
    competencies: ["Describes objects using clues", "Guesses from descriptions", "Speaks confidently"],
    bloomsProgression: [
      { day: 1, level: "Apply", focus: "Play guessing game, describe and guess objects" }] },
  { id: "2-2.3", en: "Let's Speak - What are you doing?", unit: 2, pages: "18-20", days: 2, type: "conversation" as const,
    vocabulary: ["looking", "sleeping", "reading", "drawing", "butterfly", "nest", "sky", "colours", "umbrella"],
    structures: ["What are you doing?", "I'm reading.", "What's going on?"],
    competencies: ["Uses present continuous", "Names colours", "Uses prepositions: in, under, near"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn present continuous dialogues with squirrel pictures" },
      { day: 2, level: "Apply", focus: "Find colours, use prepositions, count objects in picture" }] },
  { id: "2-2.4", en: "The Lion and the Mouse", unit: 2, pages: "20-22", days: 3, type: "story" as const,
    vocabulary: ["lion", "mouse", "sleeping", "jumped", "climbed", "angry", "trapped", "net", "gnawed", "free", "grateful", "promise"],
    structures: ["Please let me go.", "One day I will help you.", "A friend in need is a friend indeed."],
    competencies: ["Sequences story events", "Understands moral", "Narrates with picture clues"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify characters" },
      { day: 2, level: "Understand", focus: "Sequence picture cards, answer questions" },
      { day: 3, level: "Apply", focus: "Enact story, discuss moral about helping others" }] },
  { id: "2-2.5", en: "Word Basket - 'i' sound", unit: 2, pages: "23", days: 2, type: "phonics" as const,
    vocabulary: ["sit", "hit", "bit", "fit", "kit", "pit", "pin", "bin", "tin", "win", "fin", "dig", "big", "fig", "pig", "wig"],
    structures: ["The pig is big.", "Sit in the pit."],
    competencies: ["Reads CVC words with 'i'", "Builds word families", "Reads simple sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read -it, -in, -ig word families" },
      { day: 2, level: "Apply", focus: "Read sentences, build new words" }] },
  { id: "2-2.6", en: "Learning Letters H-N", unit: 2, pages: "24-25", days: 2, type: "phonics" as const,
    vocabulary: ["trace", "write", "letters", "H", "I", "J", "K", "L", "M", "N"],
    structures: ["Trace and write."],
    competencies: ["Traces and writes H-N", "Develops handwriting skills"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Trace H-K, match letters to pictures" },
      { day: 2, level: "Apply", focus: "Trace L-N, write independently" }] },
  { id: "2-2.7", en: "Tony Tinker", unit: 2, pages: "26", days: 2, type: "poem" as const,
    vocabulary: ["tinker", "tailor", "soldier", "sailor", "doctor", "farmer", "teacher", "want to be"],
    structures: ["Tony Tinker, what will you be?", "I want to be a ___."],
    competencies: ["Sings/recites poems", "Names occupations", "Expresses aspirations"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing poem, learn occupation names" },
      { day: 2, level: "Apply", focus: "Say what you want to be, draw and describe" }] },
  { id: "2-2.8", en: "Activity Time - Matching", unit: 2, pages: "27", days: 1, type: "conversation" as const,
    vocabulary: ["match", "picture", "word", "same", "different"],
    structures: ["Match the picture with the word."],
    competencies: ["Matches words to pictures", "Reads familiar words at sight"],
    bloomsProgression: [
      { day: 1, level: "Apply", focus: "Match pictures to words, categorise" }] },
  { id: "2-2.9", en: "Let's Speak - I like / I don't like", unit: 2, pages: "28", days: 2, type: "conversation" as const,
    vocabulary: ["like", "don't like", "mango", "apple", "banana", "orange", "grapes", "milk"],
    structures: ["I like ___.", "I don't like ___.", "Do you like ___?"],
    competencies: ["Expresses likes and dislikes", "Uses question forms", "Speaks about self"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn 'I like' and 'I don't like' with food items" },
      { day: 2, level: "Apply", focus: "Survey classmates about likes/dislikes, report" }] },
  { id: "2-2.10", en: "Numbers 11 to 20", unit: 2, pages: "29", days: 2, type: "conversation" as const,
    vocabulary: ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty"],
    structures: ["How many ___?", "There are ___."],
    competencies: ["Identifies numerals 11-20", "Counts objects", "Writes number words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn numbers 11-20, count objects" },
      { day: 2, level: "Apply", focus: "Count items in classroom, write number words" }] },
  { id: "2-2.11", en: "The Visit to Grandmother", unit: 2, pages: "30-32", days: 3, type: "story" as const,
    vocabulary: ["grandmother", "village", "farm", "animals", "cow", "hen", "goat", "well", "happy", "visit"],
    structures: ["We went to ___.", "I saw a ___ in the farm."],
    competencies: ["Narrates story with picture clues", "Describes a visit", "Uses past tense simply"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify farm animals" },
      { day: 2, level: "Understand", focus: "Retell story, answer questions" },
      { day: 3, level: "Apply", focus: "Draw own grandmother's house, describe visit" }] },
  // UNIT 3
  { id: "2-3.1", en: "Action Song", unit: 3, pages: "33", days: 2, type: "song" as const,
    vocabulary: ["clap", "stamp", "wave", "nod", "shake", "tap", "action", "hands", "feet"],
    structures: ["Clap your hands.", "Stamp your feet."],
    competencies: ["Sings/recites with actions", "Follows multi-step instructions", "Performs actions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing action song, perform all actions" },
      { day: 2, level: "Apply", focus: "Create new action verses, lead classmates" }] },
  { id: "2-3.2", en: "Activity Time", unit: 3, pages: "34", days: 1, type: "conversation" as const,
    vocabulary: ["sort", "group", "classify", "match"],
    structures: ["These belong together.", "This is a ___."],
    competencies: ["Classifies objects", "Sorts by category", "Works in groups"],
    bloomsProgression: [
      { day: 1, level: "Apply", focus: "Sort pictures into groups, explain reasoning" }] },
  { id: "2-3.3", en: "Let's Speak", unit: 3, pages: "35", days: 2, type: "conversation" as const,
    vocabulary: ["where", "how", "when", "what", "who", "questions"],
    structures: ["Where is the ___?", "How are you?", "What is this?"],
    competencies: ["Asks simple questions", "Responds to questions", "Uses question words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn question words: what, where, who, how" },
      { day: 2, level: "Apply", focus: "Ask and answer questions in pairs" }] },
  { id: "2-3.4", en: "Word Basket - 'e' and 'o' sounds", unit: 3, pages: "36", days: 2, type: "phonics" as const,
    vocabulary: ["pen", "hen", "ten", "men", "den", "bed", "red", "leg", "pet", "net", "hot", "pot", "dot", "cot", "lot", "fox", "box"],
    structures: ["The hen has ten eggs.", "The pot is hot."],
    competencies: ["Reads CVC words with 'e' and 'o'", "Builds word families", "Reads sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read -en, -ed, -et word families" },
      { day: 2, level: "Apply", focus: "Read -ot, -ox word families, read sentences" }] },
  { id: "2-3.5", en: "Know the Occupations", unit: 3, pages: "37-38", days: 2, type: "picture-talk" as const,
    vocabulary: ["doctor", "teacher", "farmer", "police", "driver", "cook", "nurse", "postman"],
    structures: ["A ___ helps us by ___.", "She is a ___."],
    competencies: ["Names occupations", "Describes roles", "Uses he/she correctly"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn occupation names with pictures" },
      { day: 2, level: "Apply", focus: "Describe what each person does, role-play" }] },
  { id: "2-3.6", en: "Zoom, Zoom, Zoom", unit: 3, pages: "39", days: 2, type: "song" as const,
    vocabulary: ["zoom", "rocket", "moon", "stars", "space", "five", "four", "three", "two", "one", "blast off"],
    structures: ["Zoom, zoom, zoom, we're going to the moon.", "5, 4, 3, 2, 1... Blast off!"],
    competencies: ["Sings/recites with actions", "Counts down", "Enjoys rhythm and rhyme"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing rocket song with countdown" },
      { day: 2, level: "Apply", focus: "Act out space journey, add new destinations" }] },
  { id: "2-3.7", en: "Let's Speak", unit: 3, pages: "40", days: 2, type: "conversation" as const,
    vocabulary: ["morning", "afternoon", "evening", "night", "good morning", "good afternoon", "good evening", "good night"],
    structures: ["Good morning, teacher.", "Good night, mother."],
    competencies: ["Uses greetings appropriately", "Identifies time of day", "Uses stock expressions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn greetings for different times of day" },
      { day: 2, level: "Apply", focus: "Role-play greeting in different situations" }] },
  { id: "2-3.8", en: "Word Basket - 'u' sound", unit: 3, pages: "41", days: 2, type: "phonics" as const,
    vocabulary: ["cup", "pup", "bus", "nut", "hut", "cut", "jug", "mug", "bug", "rug", "sun", "run", "fun", "bun", "gun"],
    structures: ["The pup is in the hut.", "The bug is on the rug."],
    competencies: ["Reads CVC words with 'u'", "Builds word families", "Reads simple sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read -up, -ut, -ug, -un word families" },
      { day: 2, level: "Apply", focus: "Build own CVC words, read sentences" }] },
  { id: "2-3.9", en: "Learning Letters O-U", unit: 3, pages: "42-43", days: 2, type: "phonics" as const,
    vocabulary: ["trace", "write", "O", "P", "Q", "R", "S", "T", "U"],
    structures: ["Trace and write."],
    competencies: ["Traces and writes O-U", "Develops handwriting"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Trace O-R" },
      { day: 2, level: "Apply", focus: "Trace S-U, write independently" }] },
  { id: "2-3.10", en: "Fun with Letters", unit: 3, pages: "44", days: 1, type: "phonics" as const,
    vocabulary: ["match", "puzzle", "word", "letter", "find"],
    structures: ["Find the letter.", "Match the word."],
    competencies: ["Identifies letters in words", "Solves letter puzzles", "Develops phonemic awareness"],
    bloomsProgression: [
      { day: 1, level: "Apply", focus: "Letter matching games, word puzzles" }] },
  { id: "2-3.11", en: "Reading Time", unit: 3, pages: "45", days: 1, type: "picture-talk" as const,
    vocabulary: ["reading", "passage", "picture", "story", "describe"],
    structures: ["I can see ___.", "There is a ___."],
    competencies: ["Reads simple passages", "Describes pictures", "Reads familiar words"],
    bloomsProgression: [
      { day: 1, level: "Understand", focus: "Read passage, answer picture-based questions" }] },
  // UNIT 4
  { id: "2-4.1", en: "The Squirrel", unit: 4, pages: "46", days: 2, type: "poem" as const,
    vocabulary: ["squirrel", "tail", "furry", "curly", "nuts", "tree", "climb", "playful"],
    structures: ["The squirrel has a ___.", "He likes to ___."],
    competencies: ["Recites poem", "Describes animals", "Identifies rhyming words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, describe squirrel" },
      { day: 2, level: "Apply", focus: "Draw squirrel, find rhyming words" }] },
  { id: "2-4.2", en: "Calendar", unit: 4, pages: "47", days: 2, type: "conversation" as const,
    vocabulary: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", "months", "year"],
    structures: ["There are twelve months.", "My birthday is in ___."],
    competencies: ["Names months of the year", "Reads calendar", "Tells own birthday month"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn 12 month names in order" },
      { day: 2, level: "Apply", focus: "Find birthdays on calendar, identify current month" }] },
  { id: "2-4.3", en: "Let's Speak", unit: 4, pages: "48", days: 2, type: "conversation" as const,
    vocabulary: ["birthday", "celebration", "gift", "cake", "candle", "wish", "party", "happy"],
    structures: ["Happy birthday!", "How old are you?", "I am ___ years old."],
    competencies: ["Speaks about celebrations", "Expresses wishes", "Uses age expressions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn birthday dialogues" },
      { day: 2, level: "Apply", focus: "Role-play birthday party, practice wishes" }] },
  { id: "2-4.4", en: "Who is Better?", unit: 4, pages: "49-51", days: 3, type: "story" as const,
    vocabulary: ["sun", "wind", "strong", "better", "blow", "hot", "coat", "traveller", "challenge"],
    structures: ["Who is better?", "The wind said, 'I am stronger.'", "The sun smiled."],
    competencies: ["Narrates story", "Sequences events", "Understands moral"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to sun-wind story, identify characters" },
      { day: 2, level: "Understand", focus: "Answer questions, discuss: gentleness > force" },
      { day: 3, level: "Apply", focus: "Enact story, retell in own words" }] },
  { id: "2-4.5", en: "Word Basket - blends", unit: 4, pages: "52", days: 2, type: "phonics" as const,
    vocabulary: ["stop", "step", "spot", "spin", "snap", "snip", "clap", "clip", "drop", "drum", "flag", "frog"],
    structures: ["Stop and clap.", "The frog can hop."],
    competencies: ["Reads consonant blends", "Builds blend words", "Reads sentences with blends"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read st-, sp-, sn- blend words" },
      { day: 2, level: "Apply", focus: "Read cl-, dr-, fl-, fr- blends, sentences" }] },
  { id: "2-4.6", en: "Learning Letters V-Z", unit: 4, pages: "53-54", days: 2, type: "phonics" as const,
    vocabulary: ["trace", "write", "V", "W", "X", "Y", "Z"],
    structures: ["Trace and write."],
    competencies: ["Traces and writes V-Z", "Completes alphabet", "Writes all 26 letters"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Trace V-X" },
      { day: 2, level: "Apply", focus: "Trace Y-Z, write full alphabet independently" }] },
  { id: "2-4.7", en: "Crossing the Road", unit: 4, pages: "55-56", days: 2, type: "conversation" as const,
    vocabulary: ["road", "cross", "traffic", "signal", "red", "green", "yellow", "stop", "go", "wait", "zebra crossing", "safe"],
    structures: ["Stop at the red light.", "Go at the green light.", "Look left and right."],
    competencies: ["Follows safety instructions", "Reads traffic signals", "Uses imperative sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn traffic rules: red-stop, green-go, yellow-wait" },
      { day: 2, level: "Apply", focus: "Role-play crossing road, describe rules" }] },
  { id: "2-4.8", en: "Activity Time", unit: 4, pages: "57", days: 1, type: "conversation" as const,
    vocabulary: ["sort", "match", "group", "find"],
    structures: ["Find and match.", "These go together."],
    competencies: ["Classifies objects", "Matches pairs", "Works in groups"],
    bloomsProgression: [
      { day: 1, level: "Apply", focus: "Sorting and matching activity" }] },
  { id: "2-4.9", en: "Let's Speak", unit: 4, pages: "58", days: 2, type: "conversation" as const,
    vocabulary: ["where", "how", "family", "school", "home", "market"],
    structures: ["Where do you live?", "I live near ___."],
    competencies: ["Gives personal information", "Describes location", "Speaks about self"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn location dialogues" },
      { day: 2, level: "Apply", focus: "Describe own home location, pair conversations" }] },
  { id: "2-4.10", en: "Word Building", unit: 4, pages: "59", days: 2, type: "phonics" as const,
    vocabulary: ["build", "words", "letters", "combine", "read", "write"],
    structures: ["Add ___ to make a word."],
    competencies: ["Builds words from letters", "Develops phonemic awareness", "Writes simple words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Build 3-letter words from letter cards" },
      { day: 2, level: "Apply", focus: "Build and read new words independently" }] },
  { id: "2-4.11", en: "Reading Time", unit: 4, pages: "60", days: 1, type: "picture-talk" as const,
    vocabulary: ["reading", "passage", "picture", "describe", "write"],
    structures: ["Read and answer.", "Look at the picture and write."],
    competencies: ["Reads simple passages", "Answers questions", "Writes short responses"],
    bloomsProgression: [
      { day: 1, level: "Understand", focus: "Read passage, answer questions, write 2 sentences" }] },
];

export const grade2EnglishL2AssessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  "2-A1": { name: "Unit 1: Alphabet & Phonics", lessons: ["2-1.1", "2-1.2", "2-1.3", "2-1.4", "2-1.5", "2-1.6"], focus: "Ball song, please/polite, introductions, alphabet A-Z" },
  "2-A2": { name: "Unit 1: Reading & Writing", lessons: ["2-1.7", "2-1.8", "2-1.9", "2-1.10", "2-1.11"], focus: "I want to, CVC -a words, letters A-G, animal song, picture reading" },
  "2-A3": { name: "Unit 2: Animals & Actions", lessons: ["2-2.1", "2-2.2", "2-2.3", "2-2.4", "2-2.5", "2-2.6"], focus: "Birds can fly, guessing game, present continuous, Lion & Mouse, -i words" },
  "2-A4": { name: "Unit 2: Occupations & Likes", lessons: ["2-2.7", "2-2.8", "2-2.9", "2-2.10", "2-2.11"], focus: "Tony Tinker, matching, likes/dislikes, numbers 11-20, grandmother visit" },
  "2-A5": { name: "Unit 3: Songs & Phonics", lessons: ["2-3.1", "2-3.2", "2-3.3", "2-3.4", "2-3.5", "2-3.6"], focus: "Action song, sorting, questions, -e/-o words, occupations, rocket song" },
  "2-A6": { name: "Unit 3: Greetings & Letters", lessons: ["2-3.7", "2-3.8", "2-3.9", "2-3.10", "2-3.11"], focus: "Time greetings, -u words, letters O-U, letter puzzles, reading" },
  "2-A7": { name: "Unit 4: Stories & Safety", lessons: ["2-4.1", "2-4.2", "2-4.3", "2-4.4", "2-4.5"], focus: "Squirrel, calendar/months, birthday, Sun & Wind story, blends" },
  "2-A8": { name: "Unit 4: Complete Alphabet", lessons: ["2-4.6", "2-4.7", "2-4.8", "2-4.9", "2-4.10", "2-4.11"], focus: "Letters V-Z, traffic rules, sorting, location, word building, reading" },
};
