// Balbharati Grade 1 English Curriculum Data (2025-26)
// Separate from UI translations - this is the teaching content

export interface BalbharatiLesson {
  id: string;
  unit: number;
  en: string;
  mr: string;
  hi: string;
  ur: string;
  type: string;
  pages: string;
  days: number;
  vocabulary: string[];
  structures: string[];
  competencies: string[];
  bloomsProgression: { day: number; level: string; focus: string }[];
  assessmentGroup: string;
  [key: string]: any;
}

export const balbharatiLessons: BalbharatiLesson[] = [
  { id: "1.1", unit: 1, en: "Body Body Pop Pop", mr: "शरीराचे अवयव", hi: "शरीर के अंग", ur: "جسم کے اعضاء", type: "song", pages: "1", days: 2, vocabulary: ["head","shoulders","eyes","ears","nose","mouth","hand","feet","neck","fingers","chin"], structures: ["This is my ___","Touch your ___","Show me your ___","Where is your ___?"], competencies: ["Identify and name body parts in English","Follow instructions: touch your ___","Ask and answer: What is this? This is my ___"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to song, repeat body part names, point to body parts"},{day:2,level:"Understand & Apply",focus:"Use 'This is my ___' in conversation, follow instructions independently"}], assessmentGroup: "A1" },
  { id: "1.2", unit: 1, en: "What is your name?", mr: "तुमचं नाव काय?", hi: "आपका नाम क्या है?", ur: "آپ کا نام کیا ہے؟", type: "conversation", pages: "2", days: 2, vocabulary: ["name","I am","my name is","glad","fine","thank you","how are you"], structures: ["My name is ___","I am ___","How are you?","I am fine, thank you","Glad to meet you"], competencies: ["Introduce self in English","Ask someone's name","Respond to 'How are you?'"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to dialogue, repeat introductions, learn names of classmates"},{day:2,level:"Apply",focus:"Chain drill: introduce self to 3 classmates without teacher help"}], assessmentGroup: "A1" },
  { id: "1.3", unit: 1, en: "My Home", mr: "माझे घर", hi: "मेरा घर", ur: "میرا گھر", type: "picture-talk", pages: "3", days: 3, vocabulary: ["fan","table","glass","door","chair","sofa","vase","clock","window","cupboard","television"], structures: ["This is a ___","Where is the ___?","I can see a ___"], competencies: ["Name 10+ household objects in English","Point to objects when named","Use 'This is a ___' for household items"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen and identify household objects from picture, repeat names"},{day:2,level:"Understand",focus:"Match objects to words, answer 'Where is the ___?'"},{day:3,level:"Apply",focus:"Describe own home using learned vocabulary"}], assessmentGroup: "A1" },
  { id: "1.4", unit: 1, en: "Clap your hands", mr: "टाळ्या वाजवा", hi: "ताली बजाओ", ur: "تالی بجاؤ", type: "song", pages: "4", days: 2, vocabulary: ["clap","stamp","turn around","jump","stand up","sit down","hands up","stand straight"], structures: ["Clap your hands","Stamp your feet","Listen to the music and ___"], competencies: ["Follow multi-step instructions in English","Perform actions when instructed","Give simple instructions to classmates"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn action words through song, perform actions with teacher"},{day:2,level:"Apply",focus:"Give instructions to classmates, create new verses with different actions"}], assessmentGroup: "A2" },
  { id: "1.5", unit: 1, en: "Chit Chat", mr: "गप्पा-गोष्टी", hi: "बातचीत", ur: "بات چیت", type: "conversation", pages: "5-7", days: 3, vocabulary: ["good morning","good afternoon","good evening","good night","hello","hi","bath","breakfast","lunch","dinner","play","homework","wake up","brush teeth","school uniform","school bag"], structures: ["Good morning!","What do you do in the morning?","I ___ in the morning","When do you ___?"], competencies: ["Use appropriate greetings for different times of day","Describe daily routine in simple English","Understand and follow assembly instructions"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn greetings, match greeting to time of day"},{day:2,level:"Understand",focus:"Connect greetings to daily routine, describe 'My Day' sequence"},{day:3,level:"Apply",focus:"Role-play greeting situations, describe own daily routine"}], assessmentGroup: "A2" },
  { id: "1.6", unit: 1, en: "Fun with Sounds (b-c-p-t-a)", mr: "ध्वनींशी मजा", hi: "ध्वनियों से मज़ा", ur: "آوازوں سے مزا", type: "phonics", pages: "8-9", days: 3, vocabulary: ["bat","bus","bike","box","car","cat","cow","cup","pen","puppy","pigeon","parrot","top","table","teddy","tiger","ant","apple","axe","ankle"], structures: ["cap","tap","cab","tab","bat","pat","mat","cat"], competencies: ["Recognize and produce sounds of b,c,p,t,a","Identify words beginning with these sounds","Read and write simple CVC words"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify letter shapes, hear and repeat sounds, match letters to pictures"},{day:2,level:"Understand",focus:"Connect sounds to beginning of words, sort words by starting sound"},{day:3,level:"Apply",focus:"Read CVC words independently, trace and write words"}], assessmentGroup: "A3" },
  { id: "1.7", unit: 1, en: "What can you do?", mr: "तुम्ही काय करू शकता?", hi: "आप क्या कर सकते हैं?", ur: "آپ کیا کر سکتے ہیں؟", type: "conversation", pages: "10-11", days: 2, vocabulary: ["sing","swim","play","read","jump","write","walk","dance","roar","hop","fly","run","cry","bark"], structures: ["Can you ___?","Yes, I can ___","No, I can't ___","Walk like a ___"], competencies: ["Use 'can/can't' to express ability","Perform and name action words","Play 'Queen Says' game following instructions"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn action words with TPR, answer 'Can you ___?' with yes/no"},{day:2,level:"Apply",focus:"Play Queen Says game, ask classmates 'Can you ___?' independently"}], assessmentGroup: "A2" },
  { id: "1.8", unit: 1, en: "My Classroom", mr: "माझा वर्ग", hi: "मेरी कक्षा", ur: "میری جماعت", type: "picture-talk", pages: "12-13", days: 2, vocabulary: ["book","bench","chalk","tiffin","duster","dustbin","notebook","blackboard","school bag","water-bottle","calendar","computer","bell","bookshelf","mirror"], structures: ["This is a ___","Show me the ___","Where is the ___?"], competencies: ["Name 12+ classroom objects in English","Categorize objects by where they belong","Answer 'Where is the ___?' for classroom objects"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify classroom objects from picture, repeat names"},{day:2,level:"Understand & Apply",focus:"Sort objects into school/home categories, describe own classroom"}], assessmentGroup: "A3" },
  { id: "1.9", unit: 1, en: "Fun with Sounds (d-f-m-n-e)", mr: "ध्वनींशी मजा", hi: "ध्वनियों से मज़ा", ur: "آوازوں سے مزا", type: "phonics", pages: "14-15", days: 3, vocabulary: ["duck","doll","door","den","fox","farmer","fan","fish","mug","mobile","mango","mat","nose","nail","nurse","nest","egg","elbow","elephant","eight"], structures: ["pet","met","net","bed","fed","pen","den","ten"], competencies: ["Recognize and produce sounds of d,f,m,n,e","Read and write CVC words with short e"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify letter shapes and sounds, match to pictures"},{day:2,level:"Understand",focus:"Build CVC words with short e vowel, read words aloud"},{day:3,level:"Apply",focus:"Write words from dictation, identify words in simple sentences"}], assessmentGroup: "A3" },
  { id: "1.10", unit: 1, en: "Tip-Tap, Tip-Tap", mr: "टिप-टॅप", hi: "टिप-टैप", ur: "ٹپ ٹپ", type: "poem", pages: "16", days: 2, vocabulary: ["rain","sky","sun","water","joy","tip-tap","splish-splish"], structures: ["Rain falls from the ___","The sun goes down"], competencies: ["Recite poem with rhythm and actions","Identify rhyming words","Identify alliterations"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to poem, repeat with actions, identify rhyming words"},{day:2,level:"Understand",focus:"Discuss rain/seasons, identify alliterations, create sound words"}], assessmentGroup: "A4" },
  { id: "1.11", unit: 1, en: "We want rain", mr: "आम्हाला पाऊस हवा", hi: "हमें बारिश चाहिए", ur: "ہمیں بارش چاہیے", type: "story", pages: "17-19", days: 3, vocabulary: ["cloud","peacock","fish","farmer","rain","dance","paper boats","seeds","shower","puddle"], structures: ["Please rain, I want to ___","The ___ said","Who wants rain?"], competencies: ["Listen to and understand a story with 8+ sentences","Retell story events in sequence","Answer comprehension questions"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to story, identify characters, answer 'Who wants rain?'"},{day:2,level:"Understand",focus:"Sequence story events, explain why each character wants rain"},{day:3,level:"Apply",focus:"Retell story with dialogue, create own 'I want rain because ___' sentences"}], assessmentGroup: "A4" },
  { id: "2.1", unit: 2, en: "Vegetables", mr: "भाज्या", hi: "सब्ज़ियाँ", ur: "سبزیاں", type: "poem", pages: "20-21", days: 2, vocabulary: ["carrot","pumpkin","cabbage","peas","potato","beans","spinach","corn","brinjal","cauliflower","tomato"], structures: ["Which vegetable do you like?","I like ___","Do you like ___?"], competencies: ["Name 10+ vegetables in English","Express preference using like/don't like","Recite vegetable poem"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn vegetable names through poem, identify from pictures"},{day:2,level:"Apply",focus:"Express preferences, ask classmates what they like"}], assessmentGroup: "B1" },
  { id: "2.2", unit: 2, en: "Fingers", mr: "बोटे", hi: "उंगलियाँ", ur: "انگلیاں", type: "song", pages: "22", days: 2, vocabulary: ["thumb","index finger","middle finger","ring finger","little finger","wrist","palm","cheek","toes"], structures: ["Put a finger on your ___"], competencies: ["Name all five fingers in English","Follow body-part instructions in song"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn finger names through song with actions"},{day:2,level:"Apply",focus:"Sing independently, use finger names in conversation"}], assessmentGroup: "B1" },
  { id: "2.3", unit: 2, en: "In the Park", mr: "बागेत", hi: "बगीचे में", ur: "باغ میں", type: "picture-talk", pages: "23", days: 2, vocabulary: ["slide","swing","ladder","see-saw","bench","sandpit","fountain","merry-go-round","bicycle","flowers"], structures: ["This is a ___","I can see a ___","I like to play on the ___"], competencies: ["Name 10 park/playground objects","Describe a park scene","Express what they like to play on"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify park objects from picture, repeat names"},{day:2,level:"Apply",focus:"Describe own park/playground experience using learned words"}], assessmentGroup: "B1" },
  { id: "2.4", unit: 2, en: "Animals I Know", mr: "प्राणी", hi: "जानवर", ur: "جانور", type: "conversation", pages: "24-25", days: 3, vocabulary: ["cat","dog","cow","goat","horse","sheep","buffalo","ox","tiger","lion","deer","bear","zebra","fox","wolf","gorilla"], structures: ["___ lives in a ___","This is a ___"], competencies: ["Name 15+ animals and classify as pet/wild","Match animals to their homes","Use '___ lives in a ___' structure"], bloomsProgression: [{day:1,level:"Remember",focus:"Name animals, classify as pet or wild"},{day:2,level:"Understand",focus:"Match animals to homes"},{day:3,level:"Apply",focus:"Describe animals, play animal guessing game"}], assessmentGroup: "B2" },
  { id: "2.5", unit: 2, en: "Fun with Sounds (h-l-r-s-i)", mr: "ध्वनींशी मजा", hi: "ध्वनियों से मज़ा", ur: "آوازوں سے مزا", type: "phonics", pages: "26-27", days: 3, vocabulary: ["hat","hen","hill","hut","lamp","lion","lock","lemon","rat","rose","ring","ruler","soap","sun","sofa","socks","injection","igloo","insect","inkpot"], structures: ["-ip words: hip,nip,sip,lip,tip","-it words: bit,fit,hit,lit,sit,pit"], competencies: ["Recognize and produce sounds of h,l,r,s,i","Read and write CVC words with short i"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify letters and sounds, match to pictures"},{day:2,level:"Understand",focus:"Build -ip and -it word families, read aloud"},{day:3,level:"Apply",focus:"Write words from dictation, complete missing letter exercises"}], assessmentGroup: "B3" },
  { id: "2.6", unit: 2, en: "Birds can fly", mr: "पक्षी उडू शकतात", hi: "पक्षी उड़ सकते हैं", ur: "پرندے اڑ سکتے ہیں", type: "song", pages: "28-29", days: 3, vocabulary: ["fly","jump","run","hop","swim","walk","crow","sparrow","crane","eagle","peacock","pigeon","owl","parrot","feather","wing","tail","beak","leg","claws"], structures: ["Birds can ___","___ can ___","I can ___ too"], competencies: ["Name 8+ birds and their body parts","Use 'can' with action words","Sing poem with actions independently"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn bird names and action words through song"},{day:2,level:"Understand",focus:"Match birds to actions, learn bird body parts"},{day:3,level:"Apply",focus:"Create sentences, describe a bird using body part vocabulary"}], assessmentGroup: "B2" },
  { id: "2.7", unit: 2, en: "Birthday Party", mr: "वाढदिवसाची पार्टी", hi: "जन्मदिन की पार्टी", ur: "سالگرہ کی پارٹی", type: "picture-talk", pages: "30-31", days: 2, vocabulary: ["balloons","toys","gift","mask","greeting cards","birthday caps","camera","toffees","flowers","snacks","candle","crown"], structures: ["How are you?","I am fine","Where are you going?","Can you play with me?"], competencies: ["Name party-related objects","Use social conversation"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify party objects, practise greetings dialogue"},{day:2,level:"Apply",focus:"Role-play party conversation with a partner"}], assessmentGroup: "B2" },
  { id: "2.8", unit: 2, en: "Fun with Sounds (g-j-k-q-o)", mr: "ध्वनींशी मजा", hi: "ध्वनियों से मज़ा", ur: "آوازوں سے مزا", type: "phonics", pages: "32-33", days: 3, vocabulary: ["grass","gate","goat","guitar","jacket","jar","joker","jackal","kangaroo","key","kite","kettle","queen","quill","question","queue","orange","ox","owl","ostrich"], structures: ["-og words: dog,fog,jog,log","-op words: cop,hop,mop,top,pop","-ot words: dot,got,hot,pot,not"], competencies: ["Recognize and produce sounds of g,j,k,q,o","Read and write CVC words with short o"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify letters and sounds, match to pictures"},{day:2,level:"Understand",focus:"Build -og, -op, -ot word families, read aloud"},{day:3,level:"Apply",focus:"Write words from dictation, complete exercises"}], assessmentGroup: "B3" },
  { id: "2.9", unit: 2, en: "Water Bell", mr: "पाण्याची घंटा", hi: "पानी की घंटी", ur: "پانی کی گھنٹی", type: "instructions", pages: "34", days: 1, vocabulary: ["water-bottle","open","close","drink","lid","bag"], structures: ["Take out your ___","Open the ___","Drink water"], competencies: ["Follow sequential instructions in English","Understand classroom routine commands"], bloomsProgression: [{day:1,level:"Remember & Apply",focus:"Follow water bell instructions, practise giving instructions to partner"}], assessmentGroup: "B2" },
  { id: "2.10", unit: 2, en: "Who ate the butter?", mr: "लोणी कोणी खाल्लं?", hi: "मक्खन किसने खाया?", ur: "مکھن کس نے کھایا؟", type: "story", pages: "35-37", days: 3, vocabulary: ["cats","butter","monkey","fight","equal","parts","bigger","smaller","bite","finished"], structures: ["It's mine!","Don't fight","I shall make two equal parts"], competencies: ["Listen to and retell a story with moral","Use dialogue in storytelling","Understand concept of sharing"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to story, identify characters, answer basic questions"},{day:2,level:"Understand",focus:"Sequence story events, explain what went wrong"},{day:3,level:"Apply",focus:"Enact story with dialogue, narrate story from pictures"}], assessmentGroup: "B4" },
  { id: "3.1", unit: 3, en: "Traffic Signals", mr: "वाहतुकीचे संकेत", hi: "ट्रैफिक सिग्नल", ur: "ٹریفک سگنل", type: "song", pages: "38-40", days: 3, vocabulary: ["red","yellow","green","stop","wait","go","light","orange","blue","violet","pink","brown","black","white"], structures: ["Red light means ___","Stop!","Go!","Wait!"], competencies: ["Name all basic colours in English","Understand traffic signal rules","Identify VIBGYOR colours"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn traffic signal song, name 3 signal colours and meanings"},{day:2,level:"Understand",focus:"Learn all colour names, identify colours of objects"},{day:3,level:"Apply",focus:"Colour pictures correctly, describe objects using colour words"}], assessmentGroup: "C1" },
  { id: "3.2", unit: 3, en: "Vehicles", mr: "वाहने", hi: "वाहन", ur: "گاڑیاں", type: "picture-talk", pages: "41-42", days: 2, vocabulary: ["car","bus","train","bicycle","auto-rickshaw","aeroplane","boat","ship","helicopter","tractor","motorcycle","van"], structures: ["This is a ___","Where are you going?","Happy journey"], competencies: ["Name 12 vehicles","Use travel-related conversation","Enact bus-stop conversation"], bloomsProgression: [{day:1,level:"Remember",focus:"Name vehicles from picture, categorize by land/water/air"},{day:2,level:"Apply",focus:"Role-play bus-stop conversation with partner"}], assessmentGroup: "C1" },
  { id: "3.3", unit: 3, en: "Lunch Time", mr: "जेवणाची वेळ", hi: "खाने का समय", ur: "کھانے کا وقت", type: "instructions", pages: "43", days: 1, vocabulary: ["queue","plate","wash hands","sit","food","lunch","don't waste"], structures: ["Make a queue","Take your plate","Don't waste food"], competencies: ["Follow lunch-time sequential instructions","Understand hygiene-related commands"], bloomsProgression: [{day:1,level:"Remember & Apply",focus:"Follow lunch instructions, practise giving instructions"}], assessmentGroup: "C1" },
  { id: "3.4", unit: 3, en: "Fun with Sounds (v-w-x-y-z-u)", mr: "ध्वनींशी मजा", hi: "ध्वनियों से मज़ा", ur: "آوازوں سے مزا", type: "phonics", pages: "44-45", days: 3, vocabulary: ["van","violin","vulture","vegetable","well","wood","wall","watch","x-ray","xerox","yak","yoga","yarn","yacht","zip","zoo","zebra","zero","umbrella","umpire","uncle"], structures: ["-ug words: bug,jug,rug,hug,mug","-un words: fun,run,sun,gun,bun","-ut words: but,gut,cut,hut,nut"], competencies: ["Recognize and produce sounds of v,w,x,y,z,u","Complete the full alphabet a-z","Read and write CVC words with short u"], bloomsProgression: [{day:1,level:"Remember",focus:"Identify final set of letters, sounds, and pictures"},{day:2,level:"Understand",focus:"Build -ug, -un, -ut word families"},{day:3,level:"Apply",focus:"Write words from dictation, now knows all 26 letter sounds"}], assessmentGroup: "C2" },
  { id: "3.5", unit: 3, en: "Alphabet Song", mr: "अक्षरांचे गाणे", hi: "अक्षरों का गाना", ur: "حروف کا گانا", type: "song", pages: "46-47", days: 2, vocabulary: ["all 26 letters with key words and sounds"], structures: ["___ says ___ ___-___-___"], competencies: ["Sing alphabet song with letter sounds","Recognize sight words"], bloomsProgression: [{day:1,level:"Remember",focus:"Sing alphabet song connecting letters to sounds"},{day:2,level:"Understand",focus:"Read common sight words, identify them in context"}], assessmentGroup: "C2" },
  { id: "3.6", unit: 3, en: "Capital Letters - Small Letters", mr: "मोठी अक्षरे - छोटी अक्षरे", hi: "बड़े अक्षर - छोटे अक्षर", ur: "بڑے حروف - چھوٹے حروف", type: "writing", pages: "48", days: 2, vocabulary: ["A-Z capital letters","a-z small letters"], structures: [], competencies: ["Write all 26 capital and small letters","Match capital to small letters"], bloomsProgression: [{day:1,level:"Remember",focus:"Trace capital and small letters Aa through Mm"},{day:2,level:"Apply",focus:"Trace Nn through Zz, write letters independently"}], assessmentGroup: "C2" },
  { id: "3.7", unit: 3, en: "Days of the Week", mr: "आठवड्याचे दिवस", hi: "सप्ताह के दिन", ur: "ہفتے کے دن", type: "song", pages: "49-50", days: 2, vocabulary: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"], structures: ["Today is ___","Yesterday was ___","Tomorrow is ___"], competencies: ["Name all 7 days in order","Use today/yesterday/tomorrow correctly"], bloomsProgression: [{day:1,level:"Remember",focus:"Sing days song, name days in order"},{day:2,level:"Apply",focus:"Use today/yesterday/tomorrow in conversation"}], assessmentGroup: "C3" },
  { id: "3.8", unit: 3, en: "Word Family", mr: "शब्द कुटुंब", hi: "शब्द परिवार", ur: "لفظ کا خاندان", type: "phonics", pages: "51-53", days: 3, vocabulary: ["word families: -en,-an,-in,-op,-un"], structures: [], competencies: ["Build words from word families","Break compound words into parts","Find words in a word search"], bloomsProgression: [{day:1,level:"Remember",focus:"Build words using word family endings"},{day:2,level:"Understand",focus:"Break words: man-go, pen-cil. Write first letters"},{day:3,level:"Apply",focus:"Complete word search puzzle, write words independently"}], assessmentGroup: "C3" },
  { id: "3.9", unit: 3, en: "Numbers", mr: "संख्या", hi: "गिनती", ur: "نمبر", type: "conversation", pages: "54-56", days: 3, vocabulary: ["zero","one","two","three","four","five","six","seven","eight","nine","ten","dot","line","circle","triangle","square","star","arrow"], structures: ["How many ___ do you have?","I have ___ ___","Please give me ___"], competencies: ["Count and name numbers 0-10 in English","Name basic shapes","Use polite requests"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn number words 0-10, match numeral to word"},{day:2,level:"Understand",focus:"Learn shape names, count objects"},{day:3,level:"Apply",focus:"Conversation: 'How many ___?', polite requests role-play"}], assessmentGroup: "C3" },
  { id: "3.10", unit: 3, en: "The Ant and the Pigeon", mr: "मुंगी आणि कबुतर", hi: "चींटी और कबूतर", ur: "چیونٹی اور کبوتر", type: "story", pages: "57-58", days: 3, vocabulary: ["ant","pigeon","pond","leaf","hunter","gun","bit","flew away","climbed","threw","cried","missed"], structures: [], competencies: ["Listen to and retell a moral story","Sequence events using pictures","Understand the moral: help others"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to story, identify characters and key events"},{day:2,level:"Understand",focus:"Sequence events, explain cause and effect"},{day:3,level:"Apply",focus:"Retell story with dialogue, discuss moral"}], assessmentGroup: "C4" },
  { id: "4.1", unit: 4, en: "Months of the Year", mr: "वर्षातील महिने", hi: "साल के महीने", ur: "سال کے مہینے", type: "song", pages: "59-60", days: 2, vocabulary: ["January","February","March","April","May","June","July","August","September","October","November","December"], structures: ["The year starts with ___","My birthday is in ___"], competencies: ["Name all 12 months in order","Identify own birthday month"], bloomsProgression: [{day:1,level:"Remember",focus:"Sing months song, learn month names in order"},{day:2,level:"Apply",focus:"Complete missing letters in month names, tell own birthday month"}], assessmentGroup: "D1" },
  { id: "4.2", unit: 4, en: "Greetings", mr: "शुभेच्छा", hi: "शुभकामनाएँ", ur: "مبارکباد", type: "conversation", pages: "61", days: 2, vocabulary: ["Happy Birthday","Merry Christmas","Happy Diwali","Eid Mubarak","Happy New Year","Congratulations","Thank you","All the best"], structures: ["Happy ___!","Thank you!","Congratulations!"], competencies: ["Use appropriate greetings for festivals and occasions","Practise short greeting conversations"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn greeting phrases for different occasions"},{day:2,level:"Apply",focus:"Role-play greeting conversations for different situations"}], assessmentGroup: "D1" },
  { id: "4.3", unit: 4, en: "After My Bath", mr: "आंघोळीनंतर", hi: "नहाने के बाद", ur: "نہانے کے بعد", type: "poem", pages: "62-63", days: 2, vocabulary: ["bath","wipe","dry","hands","fingers","toes","legs","nose","shake","soap","bucket","shampoo","towel","toothbrush","toothpaste","mug","tap","basin","shower"], structures: ["After my bath, I try to ___"], competencies: ["Recite poem with actions","Identify rhyming word pairs","Name bathroom objects"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to poem, identify rhyming pairs, learn bathroom vocabulary"},{day:2,level:"Apply",focus:"Recite poem independently, name bathroom objects from picture"}], assessmentGroup: "D1" },
  { id: "4.4", unit: 4, en: "Chit Chat", mr: "गप्पा-गोष्टी", hi: "बातचीत", ur: "بات چیت", type: "conversation", pages: "64", days: 2, vocabulary: ["where","on the table","under the chair","in the bag","look","check","thank you"], structures: ["Where is my ___?","Look on the ___","Check under the ___","Here it is!"], competencies: ["Use prepositions: on, under, in","Ask and answer location questions"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn prepositions through dialogue, repeat conversation"},{day:2,level:"Apply",focus:"Play hide-and-find game using prepositions"}], assessmentGroup: "D2" },
  { id: "4.5", unit: 4, en: "Lost and Found", mr: "हरवलेले आणि सापडलेले", hi: "खोया और पाया", ur: "کھویا اور پایا", type: "story", pages: "65-68", days: 3, vocabulary: ["whistle","sparrow","crow","owl","duck","robin","found","lost","mine","yours","sad","happy","angry","scared"], structures: ["Is this yours?","No, it's not mine","It's mine!","Don't worry"], competencies: ["Retell story with dialogue","Use possessives: mine, yours","Express emotions"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to story, identify birds, answer basic questions"},{day:2,level:"Understand",focus:"Learn mine/yours, practise emotions vocabulary"},{day:3,level:"Apply",focus:"Enact story as birds, express emotions"}], assessmentGroup: "D2" },
  { id: "4.6", unit: 4, en: "My Kitchen", mr: "माझे स्वयंपाकघर", hi: "मेरा रसोईघर", ur: "میرا باورچی خانہ", type: "picture-talk", pages: "69-70", days: 2, vocabulary: ["mixer","ladle","fridge","gas-stove","saucer","dishes","lighter","pot","rolling pin","pan","tap","cooker","glass","jug","lemon","sugar","salt","spoon"], structures: ["This is a ___","Take some ___","Add some ___"], competencies: ["Name 12+ kitchen objects","Follow recipe instructions","Use sequence words: first, then, next"], bloomsProgression: [{day:1,level:"Remember",focus:"Name kitchen objects from picture"},{day:2,level:"Apply",focus:"Follow sharbat recipe instructions, describe steps in order"}], assessmentGroup: "D2" },
  { id: "4.7", unit: 4, en: "Our Community Helpers", mr: "आमचे समुदाय सेवक", hi: "हमारे सामुदायिक सहायक", ur: "ہمارے معاشرتی مددگار", type: "song", pages: "71-72", days: 2, vocabulary: ["doctor","teacher","farmer","soldier","driver","police","tailor"], structures: ["I am a ___","What job do you want to do?"], competencies: ["Name 7 community helpers and their roles","Express career aspirations"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn helper names and roles through song"},{day:2,level:"Apply",focus:"Role-play: 'I am a ___, I ___'"}], assessmentGroup: "D3" },
  { id: "4.8", unit: 4, en: "The Magic Fish", mr: "जादूचा मासा", hi: "जादू की मछली", ur: "جادو کی مچھلی", type: "story", pages: "73-75", days: 3, vocabulary: ["magic fish","dolphin","crab","seahorse","starfish","blue","orange","yellow","red","colourful","beautiful","pretty","happy","sea"], structures: ["Can we become ___?","Sure, I can make you ___","Thank you"], competencies: ["Retell story about sharing and kindness","Use colour words in context","Use adjectives"], bloomsProgression: [{day:1,level:"Remember",focus:"Listen to story, name sea animals and colours"},{day:2,level:"Understand",focus:"Connect colours to animals, understand why sea became happy"},{day:3,level:"Apply",focus:"Retell story, use adjectives to describe things"}], assessmentGroup: "D3" },
  { id: "4.9", unit: 4, en: "Thank You God", mr: "देवा, धन्यवाद", hi: "भगवान धन्यवाद", ur: "شکریہ خدا", type: "song", pages: "76", days: 2, vocabulary: ["world","sweet","food","birds","sing","everything","thank you","grandparents","stories","gift","help"], structures: ["Thank you God for ___"], competencies: ["Sing gratitude song","Express thankfulness in appropriate situations"], bloomsProgression: [{day:1,level:"Remember",focus:"Learn song, identify situations when we say thank you"},{day:2,level:"Apply",focus:"Practise saying thank you in different real situations"}], assessmentGroup: "D3" },
];

export const assessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  A1: { name: "Self & Home", lessons: ["1.1","1.2","1.3"], focus: "Body parts, self-introduction, household objects" },
  A2: { name: "Actions & Routines", lessons: ["1.4","1.5","1.7"], focus: "Action words, daily routine, greetings, can/can't" },
  A3: { name: "Phonics 1 & Classroom", lessons: ["1.6","1.8","1.9"], focus: "Letters b-c-p-t-a-d-f-m-n-e, CVC words, classroom objects" },
  A4: { name: "Nature & Stories 1", lessons: ["1.10","1.11"], focus: "Rain poem, seasons, first story comprehension" },
  B1: { name: "Food & Body 2", lessons: ["2.1","2.2","2.3"], focus: "Vegetables, fingers, park objects, likes/dislikes" },
  B2: { name: "Animals & Social", lessons: ["2.4","2.6","2.7","2.9"], focus: "Animals, birds, party vocabulary, social conversations" },
  B3: { name: "Phonics 2", lessons: ["2.5","2.8"], focus: "Letters h-l-r-s-i-g-j-k-q-o, CVC words with i and o" },
  B4: { name: "Stories 2", lessons: ["2.10"], focus: "Story retelling with dialogue, moral understanding" },
  C1: { name: "World Around Us", lessons: ["3.1","3.2","3.3"], focus: "Colours, traffic rules, vehicles, lunch-time instructions" },
  C2: { name: "Phonics 3 & Alphabet", lessons: ["3.4","3.5","3.6"], focus: "Complete alphabet, all letter sounds, capital and small letters" },
  C3: { name: "Time & Numbers", lessons: ["3.7","3.8","3.9"], focus: "Days of week, word families, numbers 0-10, shapes" },
  C4: { name: "Stories 3", lessons: ["3.10"], focus: "Moral story, sequencing, cause and effect" },
  D1: { name: "Calendar & Occasions", lessons: ["4.1","4.2","4.3"], focus: "Months, festival greetings, hygiene/bath vocabulary" },
  D2: { name: "Prepositions & Stories 4", lessons: ["4.4","4.5","4.6"], focus: "On/under/in, possessives mine/yours, emotions, kitchen" },
  D3: { name: "Community & Sharing", lessons: ["4.7","4.8","4.9"], focus: "Community helpers, colours in context, gratitude, adjectives" },
};
