// Grade 1 English (L1) — English Medium Schools
// Balbharati 2025-26 — "English Balbharati Grade One"
// 44 lessons across 4 units
// This is the FIRST LANGUAGE textbook (different from L2 for non-English medium)

export interface BalbharatiL1Lesson {
  id: string; en: string; mr: string; hi: string; ur: string;
  unit: number; pages: string; days: number; type: "poem" | "song" | "phonics" | "conversation" | "story" | "picture-talk";
  vocabulary: string[]; structures: string[]; competencies: string[];
  bloomsProgression: { day: number; level: string; focus: string }[];
}

export const grade1EnglishL1Lessons: BalbharatiL1Lesson[] = [
  { id: "L1-1.1", en: "My First Day", mr: "माझा पहिला दिवस", hi: "मेरा पहला दिन", ur: "میرا پہلا دن", unit: 1, pages: "1", days: 2, type: "poem",
    vocabulary: ["skip", "run", "school", "walk", "grin", "bell", "jump", "play", "grade", "hurray"],
    structures: ["See me ___.", "I'm going to ___."],
    competencies: ["Listens to songs/poems with attention", "Sings/recites poems with actions", "Speaks about first day"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to poem, repeat with actions, learn vocabulary" },
      { day: 2, level: "Understand", focus: "Understand poem, talk about own first day, use structures" }] },
  { id: "L1-1.2", en: "Clap your hands", mr: "टाळ्या वाजवा", hi: "ताली बजाओ", ur: "تالی بجاؤ", unit: 1, pages: "2", days: 2, type: "song",
    vocabulary: ["clap", "hands", "nod", "head", "stamp", "foot", "bend", "knee", "buckle", "shoe", "floor", "turn around"],
    structures: ["___ your ___ when I say ___.", "Clap your hands and ___."],
    competencies: ["Follows multi-step instructions", "Performs actions for words", "Sings with rhythm and actions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn action words: clap, nod, stamp, bend. Sing with actions" },
      { day: 2, level: "Apply", focus: "Replace actions to create new verses, TPR activity" }] },
  { id: "L1-1.3", en: "I know my alphabet", mr: "मला अक्षरे माहीत आहेत", hi: "मुझे अक्षर पता है", ur: "مجھے حروف آتے ہیں", unit: 1, pages: "3-4", days: 3, type: "phonics",
    vocabulary: ["alphabet", "apple", "ball", "cat", "dog", "elephant", "fish", "goat", "hen", "ink", "jug", "kite", "lion", "mango"],
    structures: ["A for Apple.", "I know my alphabet."],
    competencies: ["Recognises all 26 letters", "Associates letters with sounds", "Identifies beginning sounds"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Identify letters A-M with sounds and pictures" },
      { day: 2, level: "Remember", focus: "Identify letters N-Z with sounds and pictures" },
      { day: 3, level: "Apply", focus: "Sound games, word building, identify beginning sounds" }] },
  { id: "L1-1.4", en: "Let us read", mr: "चला वाचूया", hi: "चलो पढ़ें", ur: "آؤ پڑھیں", unit: 1, pages: "5-6", days: 3, type: "phonics",
    vocabulary: ["bat", "cat", "mat", "rat", "sat", "hat", "fan", "pan", "van", "can", "man", "pin", "bin", "tin", "win"],
    structures: ["The ___ sat on the ___.", "I can see a ___."],
    competencies: ["Breaks words into syllables", "Reads CVC words", "Builds words using letter sounds"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read -at words: bat, cat, mat, rat, sat, hat" },
      { day: 2, level: "Remember", focus: "Read -an and -in words: fan, pan, van, pin, bin, tin" },
      { day: 3, level: "Apply", focus: "Build own CVC words, read simple sentences" }] },
  { id: "L1-1.5", en: "Fun with Special Letters", mr: "विशेष अक्षरांशी मजा", hi: "विशेष अक्षरों से मज़ा", ur: "خاص حروف سے مزا", unit: 1, pages: "7", days: 2, type: "phonics",
    vocabulary: ["vowels", "a", "e", "i", "o", "u", "ant", "egg", "igloo", "orange", "umbrella"],
    structures: ["A E I O U are vowels."],
    competencies: ["Identifies vowels and consonants", "Recognises vowel sounds", "Separates vowel sounds from syllables"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Identify 5 vowels with picture association" },
      { day: 2, level: "Understand", focus: "Find vowels in words, sort by vowel sounds" }] },
  { id: "L1-1.6", en: "The Rainbow", mr: "इंद्रधनुष्य", hi: "इंद्रधनुष", ur: "قوس قزح", unit: 1, pages: "8-9", days: 2, type: "poem",
    vocabulary: ["rainbow", "red", "orange", "yellow", "green", "blue", "indigo", "violet", "sky", "colours"],
    structures: ["I can see a ___.", "The rainbow has ___ colours."],
    competencies: ["Names 7 rainbow colours", "Reads short poems", "Describes colours in surroundings"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to poem, learn 7 colours, sing with actions" },
      { day: 2, level: "Apply", focus: "Draw rainbow, label colours, describe surroundings" }] },
  { id: "L1-1.7", en: "Meet my family", mr: "माझ्या कुटुंबाशी भेटा", hi: "मेरे परिवार से मिलो", ur: "میرے خاندان سے ملیں", unit: 1, pages: "10", days: 2, type: "conversation",
    vocabulary: ["family", "father", "mother", "brother", "sister", "grandmother", "grandfather", "baby", "love"],
    structures: ["This is my ___.", "I love my ___."],
    competencies: ["Introduces family members", "Engages in conversation", "Uses possessive my"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn family vocabulary, introduce using This is my ___" },
      { day: 2, level: "Apply", focus: "Draw own family, describe members, pair conversation" }] },
  { id: "L1-1.8", en: "Let us know each other", mr: "चला एकमेकांना ओळखूया", hi: "चलो एक-दूसरे को जानें", ur: "آؤ ایک دوسرے کو جانیں", unit: 1, pages: "11-13", days: 3, type: "conversation",
    vocabulary: ["name", "age", "class", "friend", "teacher", "like", "favourite", "colour", "food", "game"],
    structures: ["My name is ___.", "I am ___ years old.", "My favourite ___ is ___."],
    competencies: ["Introduces self", "Asks and answers questions", "Waits for turn to speak"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Self-introduction: name, age, class" },
      { day: 2, level: "Understand", focus: "Ask questions to classmates" },
      { day: 3, level: "Apply", focus: "Pair conversations, share favourites, write about self" }] },
  { id: "L1-1.9", en: "Everybody has a name", mr: "प्रत्येकाला नाव आहे", hi: "सबका नाम है", ur: "ہر کسی کا نام ہے", unit: 1, pages: "14-15", days: 2, type: "poem",
    vocabulary: ["everybody", "name", "boy", "girl", "dog", "cat", "bird", "tree", "flower", "river"],
    structures: ["Everybody has a name.", "A ___ is called a ___."],
    competencies: ["Identifies naming words (nouns)", "Follows instructions", "Listens to poems with attention"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, identify naming words" },
      { day: 2, level: "Understand", focus: "Categorise nouns: people, animals, places, things" }] },
  { id: "L1-1.10", en: "My Daily Routine", mr: "माझी दिनचर्या", hi: "मेरी दिनचर्या", ur: "میرا روزانہ معمول", unit: 1, pages: "16-17", days: 2, type: "picture-talk",
    vocabulary: ["wake up", "brush", "bath", "breakfast", "school", "lunch", "play", "homework", "dinner", "sleep"],
    structures: ["I ___ in the morning.", "At ___ o'clock, I ___."],
    competencies: ["Describes daily activities in sequence", "Uses time vocabulary", "Predicts meaning from pictures"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn routine vocabulary with pictures, sequence activities" },
      { day: 2, level: "Apply", focus: "Describe own routine, write 3-4 sentences" }] },
  { id: "L1-2.1", en: "It's Time to Play", mr: "खेळायची वेळ", hi: "खेलने का समय", ur: "کھیلنے کا وقت", unit: 2, pages: "18", days: 2, type: "poem",
    vocabulary: ["play", "swing", "slide", "seesaw", "merry-go-round", "sand", "garden", "fun", "friends"],
    structures: ["Let's play on the ___.", "I like to ___."],
    competencies: ["Sings/recites poems", "Names playground equipment", "Expresses preferences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn playground vocabulary, sing poem" },
      { day: 2, level: "Apply", focus: "Talk about favourite activity, draw and label" }] },
  { id: "L1-2.2", en: "Avni's Visit to a Park", mr: "अवनीची उद्यानात भेट", hi: "अवनी की पार्क यात्रा", ur: "اونی کی پارک کی سیر", unit: 2, pages: "19-20", days: 2, type: "story",
    vocabulary: ["park", "trees", "flowers", "birds", "butterfly", "squirrel", "bench", "fountain", "walk", "beautiful"],
    structures: ["Avni saw a ___.", "There are ___ in the park."],
    competencies: ["Engages with non-fiction content", "Links to own experiences", "Describes places"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify things in a park" },
      { day: 2, level: "Understand", focus: "Retell story, compare with own park visit" }] },
  { id: "L1-2.3", en: "In the Classroom", mr: "वर्गात", hi: "कक्षा में", ur: "کمرے میں", unit: 2, pages: "21-22", days: 2, type: "conversation",
    vocabulary: ["classroom", "blackboard", "chalk", "desk", "chair", "book", "pencil", "eraser", "bag", "ruler"],
    structures: ["This is a ___.", "Where is the ___?", "The ___ is on the ___."],
    competencies: ["Names classroom objects", "Reads multi-syllable words", "Uses prepositions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn classroom objects, point and say" },
      { day: 2, level: "Apply", focus: "Use on/in/under/near, describe positions" }] },
  { id: "L1-2.4", en: "My House", mr: "माझे घर", hi: "मेरा घर", ur: "میرا گھر", unit: 2, pages: "23-25", days: 3, type: "picture-talk",
    vocabulary: ["house", "room", "bedroom", "kitchen", "bathroom", "garden", "door", "window", "roof", "wall"],
    structures: ["My house has a ___.", "I ___ in the ___."],
    competencies: ["Names parts of a house", "Predicts meaning from pictures", "Writes own words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn house vocabulary" },
      { day: 2, level: "Understand", focus: "Describe own house, match rooms to activities" },
      { day: 3, level: "Apply", focus: "Draw house, label rooms, write 3 sentences" }] },
  { id: "L1-2.5", en: "Weather", mr: "हवामान", hi: "मौसम", ur: "موسم", unit: 2, pages: "26", days: 2, type: "poem",
    vocabulary: ["weather", "sunny", "rainy", "cloudy", "windy", "hot", "cold", "umbrella", "raincoat"],
    structures: ["Today is ___.", "When it rains, I use ___."],
    competencies: ["Describes weather", "Associates weather with items", "Listens to poems"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn weather words, sing poem" },
      { day: 2, level: "Apply", focus: "Describe today's weather, draw weather chart" }] },
  { id: "L1-2.6", en: "Magic Words", mr: "जादूचे शब्द", hi: "जादू के शब्द", ur: "جادو کے الفاظ", unit: 2, pages: "27", days: 2, type: "conversation",
    vocabulary: ["please", "thank you", "sorry", "excuse me", "welcome", "good morning", "good night"],
    structures: ["Please give me ___.", "Thank you for ___."],
    competencies: ["Uses polite expressions", "Reads with intonation", "Practises social etiquette"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn magic words: please, thank you, sorry" },
      { day: 2, level: "Apply", focus: "Role-play situations using polite words" }] },
  { id: "L1-2.7", en: "Things I Do", mr: "मी करत असलेल्या गोष्टी", hi: "जो मैं करता हूँ", ur: "جو میں کرتا ہوں", unit: 2, pages: "28-30", days: 3, type: "picture-talk",
    vocabulary: ["read", "write", "draw", "paint", "sing", "dance", "cook", "eat", "drink", "wash", "clean", "help"],
    structures: ["I can ___.", "I like to ___.", "Every day I ___."],
    competencies: ["Names activities using action words", "Follows instructions", "Writes sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn action words with pictures" },
      { day: 2, level: "Understand", focus: "Match actions to pictures, categorise by time" },
      { day: 3, level: "Apply", focus: "Write 4 sentences using I can ___, describe picture sequence" }] },
  { id: "L1-2.8", en: "Classroom Library", mr: "वर्गातील ग्रंथालय", hi: "कक्षा पुस्तकालय", ur: "کمرے کی لائبریری", unit: 2, pages: "31-32", days: 2, type: "conversation",
    vocabulary: ["library", "book", "story", "picture", "read", "borrow", "return", "shelf", "quiet", "favourite"],
    structures: ["I want to read ___.", "My favourite book is ___."],
    competencies: ["Explains book preferences", "Recognises punctuation", "Begins independent reading"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn library vocabulary, book handling" },
      { day: 2, level: "Apply", focus: "Choose a book, describe it, share with class" }] },
  { id: "L1-2.9", en: "Our Vehicles", mr: "आमची वाहने", hi: "हमारे वाहन", ur: "ہماری گاڑیاں", unit: 2, pages: "33-34", days: 2, type: "picture-talk",
    vocabulary: ["car", "bus", "train", "bicycle", "auto", "truck", "ambulance", "fire engine", "aeroplane", "boat"],
    structures: ["I go to school by ___.", "A ___ has ___ wheels."],
    competencies: ["Names vehicles", "Reads multi-syllable words", "Categorises vehicles"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn vehicle names, sort by road/water/air" },
      { day: 2, level: "Apply", focus: "Describe how you travel, draw and label" }] },
  { id: "L1-2.10", en: "Himani and the Ladybug", mr: "हिमानी आणि लेडीबग", hi: "हिमानी और लेडीबग", ur: "ہمانی اور لیڈی بگ", unit: 2, pages: "35-36", days: 2, type: "story",
    vocabulary: ["ladybug", "garden", "tiny", "red", "spots", "gentle", "careful", "leaf", "insect", "kind"],
    structures: ["Himani saw a ___.", "She said, '___.'"],
    competencies: ["Interprets character emotions", "Tells story with dialogue", "Shows kindness"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify characters and events" },
      { day: 2, level: "Understand", focus: "Retell with dialogue, discuss kindness to insects" }] },
  { id: "L1-2.11", en: "My Flower", mr: "माझे फूल", hi: "मेरा फूल", ur: "میرا پھول", unit: 2, pages: "37", days: 2, type: "poem",
    vocabulary: ["flower", "petals", "stem", "leaf", "bud", "bloom", "garden", "beautiful", "smell"],
    structures: ["My flower has ___.", "It is ___ in colour."],
    competencies: ["Names parts of a flower", "Writes picture descriptions", "Listens to nature poems"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn flower parts, sing poem" },
      { day: 2, level: "Apply", focus: "Draw flower, label parts, write 2 sentences" }] },
  { id: "L1-2.12", en: "Festivals", mr: "सण", hi: "त्योहार", ur: "تہوار", unit: 2, pages: "38-40", days: 3, type: "picture-talk",
    vocabulary: ["festival", "Diwali", "Eid", "Christmas", "Holi", "celebrate", "lights", "sweets", "family", "together"],
    structures: ["We celebrate ___.", "On ___, we ___."],
    competencies: ["Talks about festivals", "Engages with non-fiction", "Reads passages with intonation"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn festival names, match to pictures" },
      { day: 2, level: "Understand", focus: "Describe favourite festival celebration" },
      { day: 3, level: "Apply", focus: "Draw and write about favourite festival" }] },
  { id: "L1-3.1", en: "Opposites", mr: "विरुद्धार्थी शब्द", hi: "विलोम शब्द", ur: "متضاد الفاظ", unit: 3, pages: "41", days: 2, type: "poem",
    vocabulary: ["big", "small", "tall", "short", "hot", "cold", "fast", "slow", "up", "down", "happy", "sad", "open", "close"],
    structures: ["___ is the opposite of ___."],
    competencies: ["Identifies opposite pairs", "Creates short rhymes", "Uses adjectives"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn 7 opposite pairs with actions" },
      { day: 2, level: "Apply", focus: "Create own opposite sentences, play game" }] },
  { id: "L1-3.2", en: "Suyog makes friends", mr: "सुयोग मित्र बनवतो", hi: "सुयोग दोस्त बनाता है", ur: "سویوگ دوست بناتا ہے", unit: 3, pages: "42-43", days: 2, type: "story",
    vocabulary: ["friend", "new", "school", "shy", "smile", "share", "play", "together", "kind", "brave"],
    structures: ["Will you be my friend?", "Let's play together."],
    competencies: ["Interprets character emotions", "Talks about friendship", "Narrates with dialogue"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify how Suyog makes friends" },
      { day: 2, level: "Apply", focus: "Role-play making friends, discuss kindness" }] },
  { id: "L1-3.3", en: "The Fox and the Crow", mr: "कोल्हा आणि कावळा", hi: "लोमड़ी और कौआ", ur: "لومڑی اور کوا", unit: 3, pages: "44", days: 2, type: "story",
    vocabulary: ["fox", "crow", "cheese", "tree", "clever", "foolish", "sing", "beautiful", "voice", "drop"],
    structures: ["The fox said, '___.'"],
    competencies: ["Interprets plot and emotions", "Sequences events", "Writes picture descriptions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen, sequence 4 picture cards" },
      { day: 2, level: "Understand", focus: "Discuss moral, retell in own words" }] },
  { id: "L1-3.4", en: "Books are my best friends", mr: "पुस्तके माझे जिवलग मित्र", hi: "किताबें मेरी सबसे अच्छी दोस्त", ur: "کتابیں میری سب سے اچھی دوست", unit: 3, pages: "45", days: 2, type: "conversation",
    vocabulary: ["books", "read", "stories", "learn", "imagine", "adventure", "knowledge", "library"],
    structures: ["Books help me ___.", "I like books because ___."],
    competencies: ["Begins independent reading", "Explains book preferences", "Reads regularly"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Discuss favourite books, types of books" },
      { day: 2, level: "Apply", focus: "Choose book, describe to partner" }] },
  { id: "L1-3.5", en: "Open a book", mr: "पुस्तक उघडा", hi: "किताब खोलो", ur: "کتاب کھولو", unit: 3, pages: "46-47", days: 2, type: "poem",
    vocabulary: ["open", "book", "world", "dream", "fly", "ocean", "mountain", "magic", "imagine"],
    structures: ["Open a book and ___."],
    competencies: ["Sings/recites poems", "Begins independent reading", "Connects reading to imagination"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, discuss what books show us" },
      { day: 2, level: "Apply", focus: "Draw what you imagine, share with class" }] },
  { id: "L1-3.6", en: "Raghu goes to the market", mr: "रघू बाजारात जातो", hi: "रघु बाज़ार जाता है", ur: "راغو بازار جاتا ہے", unit: 3, pages: "48-50", days: 3, type: "story",
    vocabulary: ["market", "vegetables", "fruits", "buy", "money", "bag", "shop", "seller", "carrots", "potatoes", "tomatoes", "bananas"],
    structures: ["Please give me ___.", "How much is the ___?"],
    competencies: ["Follows instructions", "Reads passages accurately", "Uses transactional language"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn market vocabulary" },
      { day: 2, level: "Understand", focus: "Read story, practise dialogue" },
      { day: 3, level: "Apply", focus: "Role-play market scene" }] },
  { id: "L1-3.7", en: "The Squirrel", mr: "खार", hi: "गिलहरी", ur: "گلہری", unit: 3, pages: "51", days: 2, type: "poem",
    vocabulary: ["squirrel", "tail", "furry", "nuts", "tree", "climb", "jump", "quick", "brown"],
    structures: ["The squirrel has a ___.", "It can ___."],
    competencies: ["Sings/recites poems", "Describes animals", "Uses adjectives"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, describe squirrel" },
      { day: 2, level: "Apply", focus: "Compare with another animal, draw and write" }] },
  { id: "L1-3.8", en: "Alia falls sick", mr: "आलियाला बरे वाटत नाही", hi: "आलिया बीमार पड़ती है", ur: "عالیہ بیمار ہوتی ہے", unit: 3, pages: "52-54", days: 3, type: "story",
    vocabulary: ["sick", "doctor", "medicine", "fever", "cough", "rest", "care", "mother", "healthy", "food"],
    structures: ["Alia has a ___.", "The doctor said, '___.'"],
    competencies: ["Engages in health conversation", "Gives instructions", "Reads and follows instructions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, learn health vocabulary" },
      { day: 2, level: "Understand", focus: "Discuss healthy habits" },
      { day: 3, level: "Apply", focus: "Role-play doctor-patient, write 3 healthy habits" }] },
  { id: "L1-3.9", en: "The Ant and the Grasshopper", mr: "मुंगी आणि नाकतोडा", hi: "चींटी और टिड्डा", ur: "چیونٹی اور ٹڈا", unit: 3, pages: "55-56", days: 2, type: "story",
    vocabulary: ["ant", "grasshopper", "summer", "winter", "work", "play", "food", "store", "lazy", "hardworking"],
    structures: ["The ant said, '___.'", "In summer, the ___."],
    competencies: ["Interprets plot and emotions", "Narrates own stories", "Understands morals"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen, identify characters and behaviour" },
      { day: 2, level: "Understand", focus: "Discuss moral: work hard. Compare characters" }] },
  { id: "L1-3.10", en: "Minku, the Monkey", mr: "मिंकू, माकड", hi: "मिंकू, बंदर", ur: "منکو، بندر", unit: 3, pages: "57-58", days: 2, type: "story",
    vocabulary: ["monkey", "banana", "tree", "naughty", "swing", "tail", "jungle", "friends", "share", "climb"],
    structures: ["Minku likes to ___.", "He ___ from tree to tree."],
    competencies: ["Tells story with dialogue", "Describes animal characters", "Uses action words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen, describe what Minku does" },
      { day: 2, level: "Apply", focus: "Enact story, create own animal story" }] },
  { id: "L1-3.11", en: "My Kitty Cat", mr: "माझे माजर", hi: "मेरी बिल्ली", ur: "میری بلی", unit: 3, pages: "59-60", days: 2, type: "poem",
    vocabulary: ["cat", "kitty", "soft", "fur", "purr", "milk", "play", "yarn", "whiskers", "paws", "meow"],
    structures: ["My kitty cat ___.", "She likes to ___."],
    competencies: ["Sings/recites poems", "Writes sentences about pets", "Writes in conventional script"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, describe cat" },
      { day: 2, level: "Apply", focus: "Write 3 sentences about a pet, draw and label" }] },
  { id: "L1-4.1", en: "A boy went walking", mr: "एक मुलगा फिरायला गेला", hi: "एक लड़का सैर करने गया", ur: "ایک لڑکا چلنے گیا", unit: 4, pages: "61-62", days: 2, type: "story",
    vocabulary: ["boy", "walk", "cow", "horse", "pig", "duck", "hen", "farm", "animals", "follow"],
    structures: ["He saw a ___.", "The ___ followed the boy."],
    competencies: ["Sings/recites with actions", "Names farm animals", "Sequences events"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn farm animals, listen to story" },
      { day: 2, level: "Apply", focus: "Retell with actions, add more animals, enact" }] },
  { id: "L1-4.2", en: "Harry, the Hippo", mr: "हॅरी, पाणघोडा", hi: "हैरी, दरियाई घोड़ा", ur: "ہیری، دریائی گھوڑا", unit: 4, pages: "63-64", days: 2, type: "story",
    vocabulary: ["hippo", "river", "big", "swim", "mud", "mouth", "teeth", "heavy", "water", "Africa"],
    structures: ["Harry likes to ___.", "He is ___ and ___."],
    competencies: ["Reads multi-syllable words", "Recognises double consonant words", "Reads with intonation"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read story, learn about hippos, find describing words" },
      { day: 2, level: "Apply", focus: "Describe another animal, read aloud with expression" }] },
  { id: "L1-4.3", en: "Singing is Fun!", mr: "गाणे म्हणजे मजा!", hi: "गाना मज़ेदार है!", ur: "گانا مزیدار ہے!", unit: 4, pages: "65", days: 2, type: "song",
    vocabulary: ["sing", "song", "music", "clap", "tap", "hum", "melody", "rhythm", "loud", "soft"],
    structures: ["Singing is ___.", "Let's sing a ___."],
    competencies: ["Sings/recites longer poems", "Reads multi-syllable words", "Expresses joy through music"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sing the song, learn music vocabulary" },
      { day: 2, level: "Apply", focus: "Create rhythm, clap patterns, group performance" }] },
  { id: "L1-4.4", en: "A Walk in Nature", mr: "निसर्गात फेरफटका", hi: "प्रकृति में सैर", ur: "فطرت میں سیر", unit: 4, pages: "66", days: 2, type: "picture-talk",
    vocabulary: ["nature", "tree", "flower", "bird", "butterfly", "river", "mountain", "sky", "grass", "rock", "leaf"],
    structures: ["I can see a ___.", "Nature is ___."],
    competencies: ["Describes nature", "Writes picture descriptions", "Connects to experiences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn nature vocabulary from picture walk" },
      { day: 2, level: "Apply", focus: "Go outside, observe nature, draw and write" }] },
  { id: "L1-4.5", en: "The Elephant and the Ants", mr: "हत्ती आणि मुंग्या", hi: "हाथी और चींटियाँ", ur: "ہاتھی اور چیونٹیاں", unit: 4, pages: "67-68", days: 3, type: "story",
    vocabulary: ["elephant", "ants", "big", "small", "strong", "teamwork", "help", "trunk", "together", "humble"],
    structures: ["The elephant was ___.", "The ants helped by ___."],
    competencies: ["Begins independent reading", "Identifies plots and characters", "Understands teamwork"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen, identify who helped whom" },
      { day: 2, level: "Understand", focus: "Discuss moral: even small can help big" },
      { day: 3, level: "Apply", focus: "Retell, draw 4-picture sequence, write captions" }] },
  { id: "L1-4.6", en: "Off to Mars!", mr: "मंगळवर चला!", hi: "मंगल की ओर!", ur: "مریخ کی طرف!", unit: 4, pages: "69-70", days: 2, type: "story",
    vocabulary: ["Mars", "rocket", "space", "astronaut", "stars", "moon", "planet", "fly", "helmet", "adventure"],
    structures: ["Let's fly to ___.", "In space, we can see ___."],
    competencies: ["Reads unfamiliar stories with guidance", "Uses imagination", "Talks about space"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn space vocabulary, listen to story" },
      { day: 2, level: "Apply", focus: "Imagine own space trip, draw and write" }] },
  { id: "L1-4.7", en: "Honest Abhi", mr: "प्रामाणिक अभी", hi: "ईमानदार अभी", ur: "ایماندار ابھی", unit: 4, pages: "71-72", days: 2, type: "story",
    vocabulary: ["honest", "wallet", "money", "found", "return", "owner", "happy", "reward", "truth", "right"],
    structures: ["Abhi found a ___.", "He returned it because ___."],
    competencies: ["Interprets emotions", "Tells story with dialogue", "Understands honesty"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen, identify what Abhi did" },
      { day: 2, level: "Understand", focus: "Discuss honesty, what would you do, role-play" }] },
  { id: "L1-4.8", en: "A Joyful Day", mr: "आनंदाचा दिवस", hi: "खुशी का दिन", ur: "خوشی کا دن", unit: 4, pages: "73-74", days: 2, type: "picture-talk",
    vocabulary: ["joyful", "picnic", "family", "basket", "food", "games", "river", "grass", "together", "laugh"],
    structures: ["We had a ___ day.", "We played ___ together."],
    competencies: ["Describes experiences", "Writes 2-3 own sentences", "Shares personal experiences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Discuss picture, learn picnic vocabulary" },
      { day: 2, level: "Apply", focus: "Write about a happy day, draw and describe" }] },
  { id: "L1-4.9", en: "A Gift for Mother", mr: "आईसाठी भेट", hi: "माँ के लिए उपहार", ur: "ماں کے لیے تحفہ", unit: 4, pages: "75-76", days: 2, type: "story",
    vocabulary: ["gift", "mother", "love", "card", "flower", "draw", "write", "surprise", "hug", "smile"],
    structures: ["I made a ___ for my mother.", "She was ___."],
    competencies: ["Reads with intonation", "Begins independent reading", "Expresses love"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read story, discuss gifts" },
      { day: 2, level: "Apply", focus: "Make a card, write a message" }] },
  { id: "L1-4.10", en: "Cookout", mr: "स्वयंपाक", hi: "पकाना बनाना", ur: "کھانا پکانا", unit: 4, pages: "77", days: 2, type: "poem",
    vocabulary: ["cook", "recipe", "mix", "stir", "pour", "bake", "taste", "yummy", "kitchen", "ingredients"],
    structures: ["First, we ___. Then, we ___.", "It tastes ___."],
    competencies: ["Listens to poems", "Follows recipe instructions", "Reads and narrates meaning"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn cooking words, sing poem" },
      { day: 2, level: "Apply", focus: "Describe a simple recipe step by step" }] },
  { id: "L1-4.11", en: "Summer Holidays", mr: "उन्हाळ्याची सुट्टी", hi: "गर्मी की छुट्टियाँ", ur: "گرمیوں کی چھٹیاں", unit: 4, pages: "78-80", days: 3, type: "picture-talk",
    vocabulary: ["summer", "holidays", "travel", "beach", "swim", "ice cream", "grandparents", "village", "mango", "watermelon"],
    structures: ["In summer, I like to ___.", "I visited my ___."],
    competencies: ["Describes holiday experiences", "Writes about experiences", "Reads with intonation"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn summer vocabulary, discuss holidays" },
      { day: 2, level: "Understand", focus: "Share holiday memories, compare activities" },
      { day: 3, level: "Apply", focus: "Write 5 sentences about summer holidays" }] },
];

export const grade1EnglishL1AssessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  "L1-A1": { name: "Phonics & Introduction", lessons: ["L1-1.1", "L1-1.2", "L1-1.3", "L1-1.4", "L1-1.5"], focus: "Alphabet, letter sounds, CVC words, vowels, action poems" },
  "L1-A2": { name: "Family, Self & Daily Life", lessons: ["L1-1.6", "L1-1.7", "L1-1.8", "L1-1.9", "L1-1.10"], focus: "Colours, family, self-introduction, nouns, daily routine" },
  "L1-A3": { name: "My World", lessons: ["L1-2.1", "L1-2.2", "L1-2.3", "L1-2.4", "L1-2.5", "L1-2.6"], focus: "Playground, park, classroom, house, weather, polite words" },
  "L1-A4": { name: "Activities & Reading", lessons: ["L1-2.7", "L1-2.8", "L1-2.9", "L1-2.10", "L1-2.11", "L1-2.12"], focus: "Action words, library, vehicles, stories, nature, festivals" },
  "L1-A5": { name: "Stories & Values", lessons: ["L1-3.1", "L1-3.2", "L1-3.3", "L1-3.4", "L1-3.5", "L1-3.6"], focus: "Opposites, friendship, morals, reading, market" },
  "L1-A6": { name: "Animals & Health", lessons: ["L1-3.7", "L1-3.8", "L1-3.9", "L1-3.10", "L1-3.11"], focus: "Animals, health, moral stories, pets" },
  "L1-A7": { name: "Adventure & Nature", lessons: ["L1-4.1", "L1-4.2", "L1-4.3", "L1-4.4", "L1-4.5", "L1-4.6"], focus: "Farm animals, nature, space, teamwork" },
  "L1-A8": { name: "Expression & Holidays", lessons: ["L1-4.7", "L1-4.8", "L1-4.9", "L1-4.10", "L1-4.11"], focus: "Honesty, joy, gifts, cooking, summer" },
};
