// Grade 4 English (L2) — Non-English Medium Schools
// Balbharati 2025-26 — "My English Book Four"
// 6 units

export const grade4EnglishL2Lessons = [
  // Unit 1
  { id: "4-1.1", en: "A Naughty Monkey", unit: 1, pages: "1-3", days: 2, type: "story" as const,
    vocabulary: ["naughty", "monkey", "tree", "cap", "seller", "trick", "copy", "throw", "clever"],
    structures: ["The monkey took the ___.", "The seller said, '___.'"],
    competencies: ["Reads story with comprehension", "Sequences events", "Narrates with dialogue"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story, identify characters and trick" }, { day: 2, level: "Apply", focus: "Retell story, enact the scene" }] },
  { id: "4-1.2", en: "Action Time", unit: 1, pages: "4-5", days: 1, type: "conversation" as const,
    vocabulary: ["action", "instructions", "follow", "do", "show"],
    structures: ["Do this.", "Now do that.", "Follow me."],
    competencies: ["Follows multi-step instructions", "Gives instructions"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Follow and give action instructions in English" }] },
  { id: "4-1.3", en: "English Sounds", unit: 1, pages: "6-8", days: 2, type: "phonics" as const,
    vocabulary: ["sound", "letter", "blend", "digraph", "sh", "ch", "th", "wh", "ph"],
    structures: ["The sound ___ is in the word ___."],
    competencies: ["Identifies digraphs", "Reads words with sh/ch/th/wh/ph"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn digraphs sh, ch, th" }, { day: 2, level: "Apply", focus: "Learn wh, ph, find words with digraphs" }] },
  { id: "4-1.4", en: "My Bicycle", unit: 1, pages: "9-10", days: 2, type: "poem" as const,
    vocabulary: ["bicycle", "ride", "wheels", "pedal", "bell", "road", "fast", "slow", "careful", "helmet"],
    structures: ["I ride my bicycle to ___.", "My bicycle has ___."],
    competencies: ["Recites poems with expression", "Describes vehicles"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, bicycle parts vocabulary" }, { day: 2, level: "Apply", focus: "Describe own bicycle/vehicle, draw and label" }] },
  { id: "4-1.5", en: "Can and Could", unit: 1, pages: "11-12", days: 2, type: "conversation" as const,
    vocabulary: ["can", "could", "able", "ability", "past", "present", "request"],
    structures: ["I can ___.", "Could you please ___?", "When I was small, I could not ___."],
    competencies: ["Uses can/could correctly", "Makes polite requests with could"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn can (ability) and could (past/polite)" }, { day: 2, level: "Apply", focus: "Write sentences comparing abilities then and now" }] },
  { id: "4-1.6", en: "Doing Words", unit: 1, pages: "13-14", days: 2, type: "conversation" as const,
    vocabulary: ["verb", "action", "doing", "present", "past", "walk", "walked", "play", "played"],
    structures: ["Yesterday I ___.", "Today I ___."],
    competencies: ["Identifies verbs", "Uses simple present and past tense"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn verbs, present and past forms" }, { day: 2, level: "Apply", focus: "Write sentences in present and past tense" }] },
  { id: "4-1.7", en: "Revision 1", unit: 1, pages: "15-16", days: 1, type: "phonics" as const,
    vocabulary: ["revise", "practise", "test", "check"],
    structures: ["Read and answer.", "Fill in the blanks."],
    competencies: ["Revises Unit 1 content", "Self-assesses learning"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Complete revision exercises for Unit 1" }] },
  // Unit 2
  { id: "4-2.1", en: "A Collage", unit: 2, pages: "17-18", days: 2, type: "picture-talk" as const,
    vocabulary: ["collage", "cut", "paste", "picture", "magazine", "arrange", "art", "create"],
    structures: ["First, cut the ___. Then paste it on ___."],
    competencies: ["Follows craft instructions", "Describes process steps"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn collage-making vocabulary and steps" }, { day: 2, level: "Apply", focus: "Make a collage, describe process in English" }] },
  { id: "4-2.2", en: "English Sounds 2", unit: 2, pages: "19-20", days: 2, type: "phonics" as const,
    vocabulary: ["long vowel", "short vowel", "silent e", "magic e", "ai", "ee", "oa"],
    structures: ["The magic e makes the vowel say its name."],
    competencies: ["Reads long vowel words", "Understands magic e rule"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn magic e: cap-cape, pin-pine, hop-hope" }, { day: 2, level: "Apply", focus: "Read long vowel words, sort short vs long" }] },
  { id: "4-2.3", en: "Describing Words", unit: 2, pages: "21-23", days: 2, type: "conversation" as const,
    vocabulary: ["adjective", "describe", "big", "small", "red", "beautiful", "soft", "hard", "sweet", "sour"],
    structures: ["The ___ ball is ___.", "Describe the ___ using ___ words."],
    competencies: ["Identifies adjectives", "Uses adjectives to describe"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn describing words for size, colour, texture, taste" }, { day: 2, level: "Apply", focus: "Describe objects using 2-3 adjectives each" }] },
  { id: "4-2.4", en: "Position Words", unit: 2, pages: "24-25", days: 2, type: "conversation" as const,
    vocabulary: ["on", "in", "under", "behind", "between", "beside", "above", "below", "near", "far"],
    structures: ["The ___ is ___ the ___.", "Where is the ___?"],
    competencies: ["Uses prepositions of place", "Describes object positions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn position words with pictures" }, { day: 2, level: "Apply", focus: "Describe positions of objects in classroom" }] },
  { id: "4-2.5", en: "Let's speak 1", unit: 2, pages: "26", days: 1, type: "conversation" as const,
    vocabulary: ["speak", "conversation", "topic", "opinion"],
    structures: ["What do you think about ___?", "I think ___."],
    competencies: ["Expresses opinions", "Engages in conversation"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Discuss topics, express opinions in pairs" }] },
  { id: "4-2.6", en: "The Mice and the Elephants", unit: 2, pages: "27-30", days: 3, type: "story" as const,
    vocabulary: ["mice", "elephants", "village", "path", "request", "promise", "trapped", "net", "gnaw", "free", "grateful"],
    structures: ["The mice said, '___.'", "They helped by ___."],
    competencies: ["Reads fable with moral", "Identifies cause and effect", "Narrates story"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story, identify characters and problem" }, { day: 2, level: "Understand", focus: "Discuss moral: small friends can help big" }, { day: 3, level: "Apply", focus: "Retell, write summary, compare with Lion & Mouse" }] },
  { id: "4-2.7", en: "Project 1", unit: 2, pages: "31", days: 1, type: "conversation" as const,
    vocabulary: ["project", "collect", "present", "display", "information"],
    structures: ["Our project is about ___.", "We collected information on ___."],
    competencies: ["Works on group project", "Presents information"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Plan and begin a group project" }] },
  // Unit 3
  { id: "4-3.1", en: "Story with Pictures", unit: 3, pages: "32-34", days: 2, type: "story" as const,
    vocabulary: ["picture", "story", "sequence", "beginning", "middle", "end", "character"],
    structures: ["First, ___. Then, ___. Finally, ___."],
    competencies: ["Reads picture stories", "Sequences story events"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read picture story, identify sequence" }, { day: 2, level: "Apply", focus: "Create own picture story with 4 frames" }] },
  { id: "4-3.2", en: "English Sounds 3", unit: 3, pages: "35-36", days: 2, type: "phonics" as const,
    vocabulary: ["oo", "ou", "ow", "oi", "oy", "ar", "or", "er", "ir", "ur"],
    structures: ["The word ___ has the sound ___."],
    competencies: ["Reads vowel combinations", "Identifies r-controlled vowels"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn oo, ou, ow, oi sounds" }, { day: 2, level: "Apply", focus: "Learn ar, or, er sounds, read words" }] },
  { id: "4-3.3", en: "This and These / Here and There", unit: 3, pages: "37-38", days: 2, type: "conversation" as const,
    vocabulary: ["this", "that", "these", "those", "here", "there", "singular", "plural", "near", "far"],
    structures: ["This is a ___.", "These are ___.", "That ___ over there is ___."],
    competencies: ["Uses demonstrative pronouns correctly", "Distinguishes near/far reference"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn this/that (singular), these/those (plural)" }, { day: 2, level: "Apply", focus: "Point and describe using correct demonstrative" }] },
  { id: "4-3.4", en: "Picture Composition", unit: 3, pages: "39-40", days: 2, type: "picture-talk" as const,
    vocabulary: ["composition", "describe", "write", "picture", "sentence", "paragraph"],
    structures: ["In this picture, I can see ___.", "There are ___ in the picture."],
    competencies: ["Writes guided composition", "Describes pictures in sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Study picture, list things seen" }, { day: 2, level: "Apply", focus: "Write 6-8 sentences describing the picture" }] },
  { id: "4-3.5", en: "Let's speak 2", unit: 3, pages: "41", days: 1, type: "conversation" as const,
    vocabulary: ["directions", "instructions", "left", "right", "straight", "turn"],
    structures: ["Go straight, then turn ___.", "It is on your ___."],
    competencies: ["Gives and follows directions", "Uses directional language"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Give directions to places in school" }] },
  { id: "4-3.6", en: "A Pocketful of Riddles", unit: 3, pages: "42-44", days: 2, type: "conversation" as const,
    vocabulary: ["riddle", "clue", "guess", "answer", "think", "pocket"],
    structures: ["What has ___ but can't ___?", "I am ___. Who am I?"],
    competencies: ["Solves complex riddles", "Creates riddles using vocabulary"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Solve riddles, discuss clue strategies" }, { day: 2, level: "Apply", focus: "Write own riddles, share with class" }] },
  { id: "4-3.7", en: "My Body", unit: 3, pages: "45-47", days: 2, type: "picture-talk" as const,
    vocabulary: ["body", "head", "eyes", "ears", "nose", "mouth", "hands", "legs", "fingers", "toes", "healthy"],
    structures: ["I use my ___ to ___.", "We should keep our body ___."],
    competencies: ["Names body parts", "Discusses hygiene and health"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn body parts, label diagram" }, { day: 2, level: "Apply", focus: "Discuss healthy habits, write 5 sentences" }] },
  { id: "4-3.8", en: "Project 2", unit: 3, pages: "48", days: 1, type: "conversation" as const,
    vocabulary: ["project", "chart", "poster", "present"],
    structures: ["We made a chart about ___."],
    competencies: ["Creates informational charts", "Presents to class"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Create chart/poster on body parts or health" }] },
  // Unit 4
  { id: "4-4.1", en: "Festivals of India", unit: 4, pages: "49-52", days: 3, type: "picture-talk" as const,
    vocabulary: ["festival", "Diwali", "Eid", "Christmas", "Holi", "Pongal", "Baisakhi", "celebrate", "tradition", "culture"],
    structures: ["On ___, people ___.", "We celebrate ___ by ___."],
    competencies: ["Talks about Indian festivals", "Reads descriptive passages"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn about 4-5 major festivals" }, { day: 2, level: "Understand", focus: "Compare celebrations across festivals" }, { day: 3, level: "Apply", focus: "Write about your favourite festival" }] },
  { id: "4-4.2", en: "Punctuation", unit: 4, pages: "53-55", days: 2, type: "conversation" as const,
    vocabulary: ["full stop", "question mark", "exclamation", "comma", "capital letter", "punctuation"],
    structures: ["A sentence ends with a ___.", "Use a question mark when ___."],
    competencies: ["Uses punctuation correctly", "Identifies sentence types"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn full stop, question mark, exclamation mark" }, { day: 2, level: "Apply", focus: "Add punctuation to passages, write correctly" }] },
  { id: "4-4.3", en: "Reading Comprehension", unit: 4, pages: "56-58", days: 2, type: "story" as const,
    vocabulary: ["comprehension", "passage", "answer", "understand", "main idea"],
    structures: ["The passage is about ___.", "The main idea is ___."],
    competencies: ["Reads passages with understanding", "Answers questions from text"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read passage, identify key information" }, { day: 2, level: "Understand", focus: "Answer questions, find main idea" }] },
  { id: "4-4.4", en: "Letter Writing", unit: 4, pages: "59-61", days: 2, type: "conversation" as const,
    vocabulary: ["letter", "dear", "yours", "address", "date", "greeting", "body", "closing"],
    structures: ["Dear ___,", "I am writing to ___.", "Yours lovingly, ___."],
    competencies: ["Writes informal letters", "Uses letter format correctly"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn letter format: date, greeting, body, closing" }, { day: 2, level: "Apply", focus: "Write a letter to a friend about school" }] },
  { id: "4-4.5", en: "Story Writing", unit: 4, pages: "62-64", days: 3, type: "story" as const,
    vocabulary: ["story", "character", "setting", "beginning", "middle", "end", "problem", "solution"],
    structures: ["Once upon a time, ___.", "The problem was ___.", "Finally, ___."],
    competencies: ["Writes short stories", "Uses story structure"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn story structure: beginning, middle, end" }, { day: 2, level: "Apply", focus: "Plan a story with characters and problem" }, { day: 3, level: "Apply", focus: "Write complete short story" }] },
  // Unit 5
  { id: "4-5.1", en: "Pronouns", unit: 5, pages: "65-67", days: 2, type: "conversation" as const,
    vocabulary: ["pronoun", "he", "she", "it", "they", "we", "I", "you", "him", "her", "them"],
    structures: ["___ is playing.", "Give it to ___."],
    competencies: ["Identifies and uses pronouns", "Replaces nouns with pronouns"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn subject pronouns: I, you, he, she, it, we, they" }, { day: 2, level: "Apply", focus: "Replace nouns with pronouns in sentences" }] },
  { id: "4-5.2", en: "Asking Questions", unit: 5, pages: "68-70", days: 2, type: "conversation" as const,
    vocabulary: ["what", "where", "when", "who", "why", "how", "question", "answer"],
    structures: ["What is ___?", "Where did ___ go?", "Why did ___ happen?"],
    competencies: ["Frames questions using question words", "Answers questions in full sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn 6 question words with examples" }, { day: 2, level: "Apply", focus: "Frame questions for given answers, interview" }] },
  { id: "4-5.3", en: "Number Words", unit: 5, pages: "71-72", days: 2, type: "phonics" as const,
    vocabulary: ["one", "two", "three", "four", "five", "ten", "twenty", "fifty", "hundred", "first", "second", "third"],
    structures: ["There are ___ children.", "She came ___ in the race."],
    competencies: ["Reads and writes number words", "Uses ordinal numbers"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn number words 1-100, ordinals 1st-10th" }, { day: 2, level: "Apply", focus: "Write number words, use ordinals in sentences" }] },
  { id: "4-5.4", en: "Reading a Timetable", unit: 5, pages: "73-74", days: 2, type: "picture-talk" as const,
    vocabulary: ["timetable", "schedule", "period", "subject", "recess", "assembly"],
    structures: ["On Monday, the first period is ___.", "Recess is at ___."],
    competencies: ["Reads and interprets timetables", "Answers questions from timetable"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read school timetable, find information" }, { day: 2, level: "Apply", focus: "Create own ideal timetable, describe it" }] },
  { id: "4-5.5", en: "Singular and Plural", unit: 5, pages: "75-77", days: 2, type: "conversation" as const,
    vocabulary: ["singular", "plural", "one", "many", "add s", "add es", "change", "irregular"],
    structures: ["One ___, many ___.", "The plural of ___ is ___."],
    competencies: ["Forms regular and irregular plurals", "Uses plurals in sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn plural rules: -s, -es, -ies, irregular" }, { day: 2, level: "Apply", focus: "Convert singular to plural, fill in passages" }] },
  { id: "4-5.6", en: "Project 3", unit: 5, pages: "78", days: 1, type: "conversation" as const,
    vocabulary: ["project", "research", "present", "group"],
    structures: ["Our project shows ___."],
    competencies: ["Completes group project", "Presents findings"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Present group project to class" }] },
  // Unit 6
  { id: "4-6.1", en: "The Village Child", unit: 6, pages: "79-80", days: 2, type: "poem" as const,
    vocabulary: ["village", "child", "field", "river", "tree", "play", "nature", "free", "happy", "simple"],
    structures: ["The village child ___.", "In the village, there is ___."],
    competencies: ["Recites poem with expression", "Compares village and city life"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, identify images of village life" }, { day: 2, level: "Apply", focus: "Compare village child and city child, discuss" }] },
  { id: "4-6.2", en: "A Telephone Conversation", unit: 6, pages: "81-82", days: 2, type: "conversation" as const,
    vocabulary: ["telephone", "conversation", "hello", "goodbye", "speaking", "message", "call back"],
    structures: ["Hello, may I speak to ___?", "This is ___ speaking.", "Can I take a message?"],
    competencies: ["Conducts phone conversations", "Takes messages"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn phone conversation format" }, { day: 2, level: "Apply", focus: "Role-play phone calls for different purposes" }] },
  { id: "4-6.3", en: "The Hare and the Tortoise", unit: 6, pages: "83-86", days: 3, type: "story" as const,
    vocabulary: ["hare", "tortoise", "race", "fast", "slow", "proud", "steady", "nap", "finish", "winner"],
    structures: ["The hare was ___ but ___.", "Slow and steady wins the race."],
    competencies: ["Reads Aesop's fable", "Understands moral", "Writes story summary"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story, identify characters and events" }, { day: 2, level: "Understand", focus: "Discuss moral, answer questions" }, { day: 3, level: "Apply", focus: "Write summary, create alternative ending" }] },
  { id: "4-6.4", en: "Reading Comprehension 2", unit: 6, pages: "87-88", days: 2, type: "story" as const,
    vocabulary: ["passage", "comprehension", "main idea", "detail", "summary"],
    structures: ["The passage tells us about ___.", "According to the passage, ___."],
    competencies: ["Reads unseen passages", "Answers inference questions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read passage, identify facts" }, { day: 2, level: "Understand", focus: "Answer questions, make inferences" }] },
  { id: "4-6.5", en: "Essay Writing", unit: 6, pages: "89-90", days: 2, type: "conversation" as const,
    vocabulary: ["essay", "topic", "introduction", "body", "conclusion", "paragraph"],
    structures: ["My favourite ___ is ___.", "In conclusion, ___."],
    competencies: ["Writes short essays", "Organises ideas in paragraphs"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn essay structure: intro, body, conclusion" }, { day: 2, level: "Apply", focus: "Write essay on My School or My Family" }] },
  { id: "4-6.6", en: "Project 4", unit: 6, pages: "91", days: 1, type: "conversation" as const,
    vocabulary: ["project", "final", "display", "celebrate"],
    structures: ["We learned ___ this year."],
    competencies: ["Completes final project", "Reflects on learning"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Final project presentation and reflection" }] },
];

export const grade4EnglishL2AssessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  "4-A1": { name: "Unit 1: Sounds & Stories", lessons: ["4-1.1", "4-1.2", "4-1.3", "4-1.4", "4-1.5", "4-1.6", "4-1.7"], focus: "Naughty Monkey, digraphs, bicycle poem, can/could, verbs" },
  "4-A2": { name: "Unit 2: Describing & Fables", lessons: ["4-2.1", "4-2.2", "4-2.3", "4-2.4", "4-2.5", "4-2.6", "4-2.7"], focus: "Collage, magic e, adjectives, prepositions, Mice & Elephants" },
  "4-A3": { name: "Unit 3: Reading & Writing", lessons: ["4-3.1", "4-3.2", "4-3.3", "4-3.4", "4-3.5", "4-3.6", "4-3.7", "4-3.8"], focus: "Picture stories, vowel combos, this/these, composition, riddles, body" },
  "4-A4": { name: "Unit 4: Festivals & Composition", lessons: ["4-4.1", "4-4.2", "4-4.3", "4-4.4", "4-4.5"], focus: "Festivals, punctuation, comprehension, letters, story writing" },
  "4-A5": { name: "Unit 5: Grammar & Data", lessons: ["4-5.1", "4-5.2", "4-5.3", "4-5.4", "4-5.5", "4-5.6"], focus: "Pronouns, questions, numbers, timetable, plurals" },
  "4-A6": { name: "Unit 6: Stories & Expression", lessons: ["4-6.1", "4-6.2", "4-6.3", "4-6.4", "4-6.5", "4-6.6"], focus: "Village poem, phone conversation, Hare & Tortoise, essay" },
};
