// Grade 2 English (L1) — English Medium Schools
// Balbharati 2025-26 — "English Balbharati Standard Two"
// 4 units × 9 sub-lessons = 36 sub-lessons
// Structure per unit: Poem → Activity → Speaking → Story → Language Study → Poem → Speaking → Reading → Writing

export const grade2EnglishL1Lessons = [
  // UNIT 1
  { id: "2L1-1.1", en: "Bridge", mr: "पूल", hi: "पुल", ur: "پل", unit: 1, pages: "1-2", days: 2, type: "poem" as const,
    vocabulary: ["boats", "sail", "rivers", "ships", "seas", "clouds", "sky", "bridges", "heaven", "bow", "prettier", "overtops"],
    structures: ["Boats sail on the ___.", "___ are prettier than ___."],
    competencies: ["Recites poems with actions", "Identifies rainbow colours", "Responds to comprehension questions"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to poem, learn vocabulary: sail, bridges, heaven, bow" },
      { day: 2, level: "Understand", focus: "Discuss what the 'bow' refers to (rainbow), colour identification activity" }] },
  { id: "2L1-1.2", en: "Activity Time", mr: "उपक्रम", hi: "गतिविधि", ur: "سرگرمی", unit: 1, pages: "3-4", days: 2, type: "phonics" as const,
    vocabulary: ["alphabet", "vowels", "consonants", "words", "letters", "pair", "pick"],
    structures: ["Words with both ___ and ___.", "The first letter of my name is ___."],
    competencies: ["Builds words from letter pairs", "Identifies first/last letters", "Counts letters in words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Letter pair game — pick two letters, build words with both" },
      { day: 2, level: "Apply", focus: "Answer questions about own name, create word lists" }] },
  { id: "2L1-1.3", en: "Let's Speak - Welcoming Friends", mr: "बोलूया - स्वागत", hi: "बोलें - स्वागत", ur: "بولیں - خوش آمدید", unit: 1, pages: "5-6", days: 2, type: "conversation" as const,
    vocabulary: ["welcome", "hello", "school", "live", "market", "nearby", "nice", "meet", "new"],
    structures: ["Hello, I am ___.", "I live near ___.", "Welcome to our school.", "Nice to meet you."],
    competencies: ["Introduces self and others", "Uses greetings and stock expressions", "Speaks confidently about self"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn welcome dialogues, practise introductions" },
      { day: 2, level: "Apply", focus: "Role-play welcoming a new student, pair conversations" }] },
  { id: "2L1-1.4", en: "Story Time - Yash and Moti", mr: "गोष्ट - यश आणि मोती", hi: "कहानी - यश और मोती", ur: "کہانی - یش اور موتی", unit: 1, pages: "7-8", days: 3, type: "story" as const,
    vocabulary: ["shoes", "morning", "cried", "sobbed", "wagging", "barked", "hole", "rat", "nibbled", "condition"],
    structures: ["He looked everywhere.", "Thank you, ___.", "The rat had carried it."],
    competencies: ["Responds to comprehension questions", "Sequences story events", "Narrates story with clues"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify characters: Yash, Moti, rat" },
      { day: 2, level: "Understand", focus: "Answer comprehension questions, find meanings from story" },
      { day: 3, level: "Apply", focus: "Put sentences in correct order, retell story" }] },
  { id: "2L1-1.5", en: "Language Study - Naming Words", mr: "भाषा अभ्यास - नामे", hi: "भाषा अध्ययन - संज्ञा", ur: "زبان کا مطالعہ - اسم", unit: 1, pages: "9-11", days: 2, type: "conversation" as const,
    vocabulary: ["naming words", "name", "place", "animal", "thing", "boy", "girl", "family", "favourite"],
    structures: ["All the answers are naming words.", "Naming words are names of anything."],
    competencies: ["Identifies naming words (nouns)", "Categorises nouns by type", "Reads passages and underlines nouns"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn what naming words are — name, place, animal, thing" },
      { day: 2, level: "Apply", focus: "Name-Place-Animal-Thing game (Bingo), find nouns in passage" }] },
  { id: "2L1-1.6", en: "I Love Little Pussy", mr: "मला माझे माजर आवडते", hi: "मुझे बिल्ली प्यारी", ur: "مجھے بلی پیاری", unit: 1, pages: "12", days: 2, type: "poem" as const,
    vocabulary: ["pussy", "coat", "warm", "hurt", "harm", "tail", "drive", "gently", "fire", "food"],
    structures: ["I love little ___.", "If I don't hurt her, she'll ___."],
    competencies: ["Sings/recites with actions", "Identifies rhyming words", "Speaks about favourite animal"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, identify rhyming pairs: warm-harm, away-play" },
      { day: 2, level: "Apply", focus: "Talk about own pet, write sentences about favourite animal" }] },
  { id: "2L1-1.7", en: "Let's Speak - May I?", mr: "बोलूया - मी शकतो का?", hi: "बोलें - क्या मैं?", ur: "بولیں - کیا میں؟", unit: 1, pages: "13", days: 2, type: "conversation" as const,
    vocabulary: ["may", "please", "borrow", "tickets", "pluck", "sorry", "sure", "dinner", "brush"],
    structures: ["May I ___?", "Yes, you may.", "Sorry, you may not."],
    competencies: ["Uses polite forms of expression", "Uses stock expressions in interaction", "Expresses personal needs"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn 'May I' dialogues for different situations" },
      { day: 2, level: "Apply", focus: "Create own 'May I' dialogues, role-play in pairs" }] },
  { id: "2L1-1.8", en: "Reading Time - My Classroom", mr: "वाचन - माझा वर्ग", hi: "पठन - मेरी कक्षा", ur: "مطالعہ - میرا کمرہ", unit: 1, pages: "14", days: 2, type: "picture-talk" as const,
    vocabulary: ["classroom", "board", "chalk", "table", "chair", "benches", "desks", "books", "door", "windows", "cupboard", "dustbin"],
    structures: ["This is my classroom.", "There is a ___ on the wall.", "We keep our ___ there."],
    competencies: ["Reads passages correctly", "Draws pictures from description", "Describes classroom"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read passage, identify classroom objects" },
      { day: 2, level: "Apply", focus: "Draw own classroom, describe in 5 sentences" }] },
  { id: "2L1-1.9", en: "Writing Skill - Picture Composition", mr: "लेखन - चित्र वर्णन", hi: "लेखन - चित्र रचना", ur: "تحریر - تصویری تحریر", unit: 1, pages: "15-16", days: 2, type: "picture-talk" as const,
    vocabulary: ["garden", "children", "playing", "trees", "birds", "hide and seek", "farm", "farmer"],
    structures: ["There is a ___.", "Many children are ___.", "Some children are ___."],
    competencies: ["Writes guided composition", "Describes pictures with sentences", "Writes 2-3 sentences about stories"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn picture composition format, read model" },
      { day: 2, level: "Apply", focus: "Write own picture composition (5 sentences about farm)" }] },
  // UNIT 2
  { id: "2L1-2.1", en: "Chameleons", mr: "सरडे", hi: "गिरगिट", ur: "گرگٹ", unit: 2, pages: "17", days: 2, type: "poem" as const,
    vocabulary: ["chameleons", "seldom", "red", "orange", "green", "strangest", "colours", "traffic lights"],
    structures: ["Chameleons are seldom seen.", "Their colours change like ___."],
    competencies: ["Recites poems with actions", "Identifies rhyming words", "Guesses meanings from context"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, identify rhymes: seen-green, sights-lights" },
      { day: 2, level: "Apply", focus: "Colour chameleon activity, discuss colour-changing animals" }] },
  { id: "2L1-2.2", en: "Activity Time - Classify & Riddles", mr: "उपक्रम - वर्गीकरण", hi: "गतिविधि - वर्गीकरण", ur: "سرگرمی - درجہ بندی", unit: 2, pages: "18-19", days: 2, type: "conversation" as const,
    vocabulary: ["mango", "rose", "lotus", "potato", "onion", "tomato", "rabbit", "grapes", "jasmine", "snake", "elephant", "tiger", "guava", "cucumber"],
    structures: ["I have ___ but I can't ___.", "Who am I?"],
    competencies: ["Categorises naming words", "Solves riddles", "Guesses meanings using context"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Classify: fruits, vegetables, animals, flowers" },
      { day: 2, level: "Apply", focus: "Solve riddles, create own riddles" }] },
  { id: "2L1-2.3", en: "Let's Speak - Community Helpers", mr: "बोलूया - समाज सेवक", hi: "बोलें - सामुदायिक सहायक", ur: "بولیں - معاشرے کے مددگار", unit: 2, pages: "20", days: 2, type: "conversation" as const,
    vocabulary: ["doctor", "policewoman", "conductor", "farmer", "soldier", "chef"],
    structures: ["A ___ helps us by ___.", "She/He works at ___."],
    competencies: ["Speaks about community helpers", "Uses gender pronouns correctly", "Speaks confidently"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Name community helpers, describe their work" },
      { day: 2, level: "Apply", focus: "Say 2-3 lines about each helper, discuss gender roles" }] },
  { id: "2L1-2.4", en: "Story Time - Unity Is Strength", mr: "गोष्ट - एकीचे बळ", hi: "कहानी - एकता में बल", ur: "کہانی - اتحاد میں طاقت", unit: 2, pages: "21-23", days: 3, type: "story" as const,
    vocabulary: ["village", "quarrelling", "bundle", "sticks", "break", "eldest", "force", "separated", "single", "unite", "strength"],
    structures: ["They would never agree.", "The sticks did not break.", "United we stand."],
    competencies: ["Responds to comprehension questions", "Narrates story with dialogue", "Understands moral"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify what the father did" },
      { day: 2, level: "Understand", focus: "Answer questions, discuss moral: unity is strength" },
      { day: 3, level: "Apply", focus: "Enact story, relate to own family/friends" }] },
  { id: "2L1-2.5", en: "Language Study - One and Many", mr: "भाषा अभ्यास - एक आणि अनेक", hi: "भाषा अध्ययन - एक और अनेक", ur: "زبان - ایک اور بہت", unit: 2, pages: "24-26", days: 2, type: "conversation" as const,
    vocabulary: ["one", "many", "singular", "plural", "add s", "add es", "change"],
    structures: ["One ___, many ___.", "Add 's' to make it many."],
    competencies: ["Forms plurals correctly", "Reads and writes singular/plural", "Applies grammar rules"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn plural rules: add -s, add -es, irregular" },
      { day: 2, level: "Apply", focus: "Convert words to plural, fill in blanks" }] },
  { id: "2L1-2.6", en: "Friends Forever", mr: "कायमचे मित्र", hi: "हमेशा के दोस्त", ur: "ہمیشہ کے دوست", unit: 2, pages: "27-28", days: 2, type: "poem" as const,
    vocabulary: ["friends", "forever", "together", "share", "care", "play", "stay", "rain", "sunshine"],
    structures: ["Friends are ___.", "We ___ together."],
    competencies: ["Sings/recites poems", "Identifies rhyming words", "Talks about friendship"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, discuss friendship" },
      { day: 2, level: "Apply", focus: "Write about best friend, draw and describe" }] },
  { id: "2L1-2.7", en: "Let's Speak - What happened?", mr: "बोलूया - काय झाले?", hi: "बोलें - क्या हुआ?", ur: "بولیں - کیا ہوا؟", unit: 2, pages: "29", days: 2, type: "conversation" as const,
    vocabulary: ["happened", "fell", "hurt", "broke", "lost", "found", "helped"],
    structures: ["What happened?", "I fell and hurt my ___."],
    competencies: ["Uses past tense in conversation", "Narrates events", "Expresses feelings"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn past tense dialogues" },
      { day: 2, level: "Apply", focus: "Narrate an incident, role-play" }] },
  { id: "2L1-2.8", en: "Reading Time - Passage", mr: "वाचन", hi: "पठन", ur: "مطالعہ", unit: 2, pages: "30-31", days: 2, type: "story" as const,
    vocabulary: ["passage", "comprehension", "answer", "questions", "understand"],
    structures: ["Read the passage.", "Answer the questions."],
    competencies: ["Reads passages correctly", "Responds to comprehension questions", "Guesses meanings"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read passage aloud, identify key information" },
      { day: 2, level: "Understand", focus: "Answer questions, discuss main idea" }] },
  { id: "2L1-2.9", en: "Writing Skill - Describing", mr: "लेखन - वर्णन", hi: "लेखन - वर्णन", ur: "تحریر - بیان", unit: 2, pages: "32-33", days: 2, type: "picture-talk" as const,
    vocabulary: ["describe", "sentences", "adjectives", "colour", "size", "shape"],
    structures: ["It is ___ and ___.", "I can see a ___."],
    competencies: ["Writes guided composition", "Uses adjectives in writing", "Describes pictures"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn describing words, model writing" },
      { day: 2, level: "Apply", focus: "Write 5 describing sentences about a picture" }] },
  // UNIT 3
  { id: "2L1-3.1", en: "Mice", mr: "उंदीर", hi: "चूहे", ur: "چوہے", unit: 3, pages: "34", days: 2, type: "poem" as const,
    vocabulary: ["mice", "nice", "cream", "cake", "rice", "clothes", "climb", "stairs", "hide"],
    structures: ["Mice are ___.", "They like to eat ___."],
    competencies: ["Recites poems", "Identifies rhyming words", "Draws or writes in response"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, identify rhymes" },
      { day: 2, level: "Apply", focus: "Draw mice, write about what they do" }] },
  { id: "2L1-3.2", en: "Activity Time", mr: "उपक्रम", hi: "गतिविधि", ur: "سرگرمی", unit: 3, pages: "35-36", days: 2, type: "conversation" as const,
    vocabulary: ["match", "sort", "group", "compare", "different", "same"],
    structures: ["These are the same.", "These are different because ___."],
    competencies: ["Conducts activities under guidance", "Sorts and classifies", "Works in groups"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Sorting and matching activity" },
      { day: 2, level: "Apply", focus: "Create own groups, explain reasoning" }] },
  { id: "2L1-3.3", en: "Let's Speak - Congratulations", mr: "बोलूया - अभिनंदन", hi: "बोलें - बधाई", ur: "بولیں - مبارکباد", unit: 3, pages: "37", days: 2, type: "conversation" as const,
    vocabulary: ["congratulations", "proud", "welcome", "thank you", "sorry", "won", "match"],
    structures: ["Congratulations!", "I am proud of you.", "Thank you for ___."],
    competencies: ["Uses stock expressions", "Responds to greetings", "Speaks confidently"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn expressions: congratulations, proud, welcome" },
      { day: 2, level: "Apply", focus: "Role-play congratulating, thanking, apologising" }] },
  { id: "2L1-3.4", en: "Story Time - Nina's Dream", mr: "गोष्ट - निनाचे स्वप्न", hi: "कहानी - नीना का सपना", ur: "کہانی - نینا کا خواب", unit: 3, pages: "38-40", days: 3, type: "story" as const,
    vocabulary: ["dream", "fairy", "fly", "swim", "cross", "touch", "mountain", "river", "cloud", "pilot", "village"],
    structures: ["Nina wanted to ___.", "Will my wishes come true?"],
    competencies: ["Responds to comprehension questions", "Matches statements with pictures", "Rewrites with punctuation"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to story, identify Nina's wishes" },
      { day: 2, level: "Understand", focus: "Match sentences to pictures, answer questions" },
      { day: 3, level: "Apply", focus: "Write about own dream, use capital letters and full stops" }] },
  { id: "2L1-3.5", en: "Language Study - Action Words", mr: "भाषा अभ्यास - क्रिया", hi: "भाषा अध्ययन - क्रिया", ur: "زبان - فعل", unit: 3, pages: "41", days: 2, type: "conversation" as const,
    vocabulary: ["fly", "hop", "run", "jump", "sit", "clap", "swim", "draw", "dance", "cry", "write", "laugh", "sing", "throw", "walk"],
    structures: ["Words that express an action are action words."],
    competencies: ["Identifies action words (verbs)", "Performs actions for words", "Writes sentences with verbs"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn 15 action words, charades game" },
      { day: 2, level: "Apply", focus: "Circle action words in sentences, write own sentences" }] },
  { id: "2L1-3.6", en: "Five Little Seeds", mr: "पाच छोटे बी", hi: "पाँच छोटे बीज", ur: "پانچ چھوٹے بیج", unit: 3, pages: "42-43", days: 2, type: "poem" as const,
    vocabulary: ["seeds", "flowers", "weeds", "leaves", "snow", "grow", "sun", "shower", "plant", "pretty", "pink"],
    structures: ["Five little seeds are waiting to ___.", "Out comes the ___."],
    competencies: ["Recites poems with actions", "Names parts of a plant", "Finds words with double vowels"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem with actions, name plant parts" },
      { day: 2, level: "Apply", focus: "Find 'ee' words (seed, weed, need, feel), label plant diagram" }] },
  { id: "2L1-3.7", en: "Let's Speak - Good Morning", mr: "बोलूया - शुभ प्रभात", hi: "बोलें - सुप्रभात", ur: "بولیں - صبح بخیر", unit: 3, pages: "44", days: 2, type: "conversation" as const,
    vocabulary: ["good morning", "congratulations", "proud", "thank you", "welcome", "sorry"],
    structures: ["Good morning, ___.", "I am proud of you.", "You are always welcome."],
    competencies: ["Uses greetings and polite expressions", "Responds appropriately", "Speaks confidently"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Practice greetings in different situations" },
      { day: 2, level: "Apply", focus: "Create dialogues using polite expressions" }] },
  { id: "2L1-3.8", en: "Reading Time - Nani's Glasses", mr: "वाचन - नानीचा चष्मा", hi: "पठन - नानी का चश्मा", ur: "مطالعہ - نانی کا چشمہ", unit: 3, pages: "45-46", days: 3, type: "story" as const,
    vocabulary: ["glasses", "bathroom", "cupboard", "kitchen", "garden", "knitting", "yarn", "wrapped", "clues", "missing", "favourite"],
    structures: ["Where did I keep them?", "I looked everywhere.", "I found the missing ___!"],
    competencies: ["Reads passages correctly", "Identifies past tense forms", "Forms plurals"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read story, identify where Nani's glasses were found" },
      { day: 2, level: "Understand", focus: "Answer comprehension, learn past tense pairs" },
      { day: 3, level: "Apply", focus: "Retell story, complete singular-plural table" }] },
  { id: "2L1-3.9", en: "Writing Skill - Instructions", mr: "लेखन - सूचना", hi: "लेखन - निर्देश", ur: "تحریر - ہدایات", unit: 3, pages: "47-48", days: 2, type: "conversation" as const,
    vocabulary: ["instructions", "method", "add", "mix", "stir", "dip", "blow", "detergent", "lemonade", "comma"],
    structures: ["First, ___. Then, ___.", "Add ___ and mix well."],
    competencies: ["Reads and follows instructions", "Writes instructions", "Uses commas correctly"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read soap bubble instructions, learn sequencing words" },
      { day: 2, level: "Apply", focus: "Write lemonade recipe instructions, use commas" }] },
  // UNIT 4
  { id: "2L1-4.1", en: "Catch them, if you can!", mr: "पकडा त्यांना!", hi: "पकड़ो उन्हें!", ur: "پکڑو انہیں!", unit: 4, pages: "49", days: 2, type: "poem" as const,
    vocabulary: ["chickens", "hens", "chicks", "farmyard", "pens", "kitchen", "chairs", "doorstep", "stairs", "none"],
    structures: ["Chicks in the ___.", "Chicks on the ___."],
    competencies: ["Sings/recites with actions", "Uses prepositions: in, on, under", "Observes surroundings"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, identify prepositions: in, on, under" },
      { day: 2, level: "Apply", focus: "Fill prepositions, describe where you see chicks" }] },
  { id: "2L1-4.2", en: "Activity Time - Summer Cooler", mr: "उपक्रम - कैरी पन्हं", hi: "गतिविधि - कैरी पन्ना", ur: "سرگرمی - آم پنا", unit: 4, pages: "50-51", days: 2, type: "conversation" as const,
    vocabulary: ["mango", "pulp", "jaggery", "salt", "cumin", "chilled", "jar", "pour", "serve", "stir", "yummy"],
    structures: ["Take a ___.", "Add ___ and stir.", "Pour it in and serve."],
    competencies: ["Follows recipe instructions", "Conducts activities under guidance", "Uses sequence words"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read recipe dialogue, learn cooking vocabulary" },
      { day: 2, level: "Apply", focus: "Describe steps to make another drink" }] },
  { id: "2L1-4.3", en: "Let's Speak - What are they doing?", mr: "बोलूया - ते काय करतात?", hi: "बोलें - वे क्या कर रहे?", ur: "بولیں - وہ کیا کر رہے؟", unit: 4, pages: "52", days: 2, type: "conversation" as const,
    vocabulary: ["dancing", "singing", "running", "reading", "writing", "cooking", "playing", "swimming"],
    structures: ["A girl is dancing.", "They are ___."],
    competencies: ["Uses present continuous tense", "Describes actions in pictures", "Speaks confidently"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn -ing forms, describe picture actions" },
      { day: 2, level: "Apply", focus: "Describe what classmates are doing, write sentences" }] },
  { id: "2L1-4.4", en: "Story Time - What Do You See?", mr: "गोष्ट - तुला काय दिसते?", hi: "कहानी - तुम्हें क्या दिखता है?", ur: "کہانی - تمہیں کیا نظر آتا ہے؟", unit: 4, pages: "53-56", days: 3, type: "story" as const,
    vocabulary: ["prince", "archery", "wooden", "parrot", "bow", "arrow", "eye", "shoot", "focus", "goal", "test", "branch"],
    structures: ["What do you see?", "I can see only the ___.", "Focusing on your goal helps you achieve it."],
    competencies: ["Responds to comprehension questions", "Enacts familiar story", "Understands moral: focus"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Listen to Arjun-Dronacharya story, identify characters" },
      { day: 2, level: "Understand", focus: "Answer questions, discuss focus and concentration" },
      { day: 3, level: "Apply", focus: "Enact story, match sports to pictures, write about favourite sport" }] },
  { id: "2L1-4.5", en: "Language Study - Position Words", mr: "भाषा अभ्यास - स्थान शब्द", hi: "भाषा अध्ययन - स्थान शब्द", ur: "زبان - مقام کے الفاظ", unit: 4, pages: "57-59", days: 2, type: "conversation" as const,
    vocabulary: ["on", "in", "under", "near", "behind", "between", "beside", "above", "below"],
    structures: ["The ___ is on the table.", "It is under the ___.", "Words that show position are position words."],
    competencies: ["Uses prepositions correctly", "Describes positions of objects", "Draws from description"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn position words with pictures: on, in, under, behind" },
      { day: 2, level: "Apply", focus: "Fill blanks with prepositions, draw from description" }] },
  { id: "2L1-4.6", en: "My Telescope", mr: "माझी दुर्बीण", hi: "मेरी दूरबीन", ur: "میری دوربین", unit: 4, pages: "60", days: 2, type: "poem" as const,
    vocabulary: ["telescope", "sky", "solar system", "comets", "planets", "satellites", "stars", "far", "close", "whizzing"],
    structures: ["I search the sky for ___.", "They don't seem very far."],
    competencies: ["Recites poems", "Names objects in the sky", "Draws and colours"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn poem, discuss space vocabulary" },
      { day: 2, level: "Apply", focus: "Draw starry sky, name things visible in sky" }] },
  { id: "2L1-4.7", en: "Let's Speak - In the Park", mr: "बोलूया - उद्यानात", hi: "बोलें - पार्क में", ur: "بولیں - پارک میں", unit: 4, pages: "61", days: 2, type: "conversation" as const,
    vocabulary: ["park", "swing", "slide", "see-saw", "bicycle", "ice-cream", "lawn", "bench", "vendor"],
    structures: ["Do you go to a park?", "What do you play with?", "I like to ___."],
    competencies: ["Answers questions about experiences", "Speaks about preferences", "Uses question forms"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Answer questions about park activities" },
      { day: 2, level: "Apply", focus: "Describe own park visit, pair conversations" }] },
  { id: "2L1-4.8", en: "Reading Time - In the Park", mr: "वाचन - उद्यानात", hi: "पठन - पार्क में", ur: "مطالعہ - پارک میں", unit: 4, pages: "62-63", days: 2, type: "picture-talk" as const,
    vocabulary: ["picnic", "beautiful", "green", "pink", "white", "bloomed", "butterflies", "swinging", "purple"],
    structures: ["Yesterday we went to a ___.", "There were ___ flying around."],
    competencies: ["Reads passages correctly", "Fills in missing words from pictures", "Writes short sentences"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Read passage, fill missing words from picture clues" },
      { day: 2, level: "Apply", focus: "Write own park visit description" }] },
  { id: "2L1-4.9", en: "Writing Skill - Letter Writing", mr: "लेखन - पत्र", hi: "लेखन - पत्र", ur: "تحریر - خط", unit: 4, pages: "64-65", days: 2, type: "conversation" as const,
    vocabulary: ["dear", "yours", "letter", "date", "address", "holiday", "trip", "village"],
    structures: ["Dear ___,", "I am writing to tell you about ___.", "Yours lovingly, ___."],
    competencies: ["Writes guided composition", "Writes short letters", "Uses letter format"],
    bloomsProgression: [
      { day: 1, level: "Remember", focus: "Learn letter format: date, greeting, body, closing" },
      { day: 2, level: "Apply", focus: "Write a letter to friend about a trip" }] },
];

export const grade2EnglishL1AssessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  "2L1-A1": { name: "Unit 1: Bridge & Basics", lessons: ["2L1-1.1", "2L1-1.2", "2L1-1.3", "2L1-1.4", "2L1-1.5"], focus: "Poem recitation, letter games, introductions, story comprehension, naming words" },
  "2L1-A2": { name: "Unit 1: Reading & Writing", lessons: ["2L1-1.6", "2L1-1.7", "2L1-1.8", "2L1-1.9"], focus: "Pet poem, polite expressions (May I), classroom description, picture composition" },
  "2L1-A3": { name: "Unit 2: Nature & Values", lessons: ["2L1-2.1", "2L1-2.2", "2L1-2.3", "2L1-2.4", "2L1-2.5"], focus: "Chameleons, classification, community helpers, unity story, plurals" },
  "2L1-A4": { name: "Unit 2: Friends & Writing", lessons: ["2L1-2.6", "2L1-2.7", "2L1-2.8", "2L1-2.9"], focus: "Friendship poem, past tense conversation, reading comprehension, descriptive writing" },
  "2L1-A5": { name: "Unit 3: Action & Growth", lessons: ["2L1-3.1", "2L1-3.2", "2L1-3.3", "2L1-3.4", "2L1-3.5"], focus: "Mice poem, sorting, congratulations, Nina's dream, action words" },
  "2L1-A6": { name: "Unit 3: Seeds & Instructions", lessons: ["2L1-3.6", "2L1-3.7", "2L1-3.8", "2L1-3.9"], focus: "Seeds poem, greetings, Nani's glasses, instructions writing" },
  "2L1-A7": { name: "Unit 4: Focus & Space", lessons: ["2L1-4.1", "2L1-4.2", "2L1-4.3", "2L1-4.4", "2L1-4.5"], focus: "Chicks poem, recipe, present continuous, Arjun story, prepositions" },
  "2L1-A8": { name: "Unit 4: Sky & Expression", lessons: ["2L1-4.6", "2L1-4.7", "2L1-4.8", "2L1-4.9"], focus: "Telescope poem, park conversation, reading comprehension, letter writing" },
};
