// Grade 5 English (L2) — Non-English Medium Schools
// Balbharati 2025-26 — "My English Book Five"
// 6 units

export const grade5EnglishL2Lessons = [
  // Unit 1
  { id: "5-1.1", en: "My Body, My Friend", unit: 1, pages: "1-3", days: 2, type: "poem" as const,
    vocabulary: ["body", "friend", "eyes", "ears", "hands", "legs", "brain", "heart", "healthy", "strong"],
    structures: ["My body helps me ___.", "I use my ___ to ___."],
    competencies: ["Recites poem with actions", "Names body parts and functions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, body parts and their uses" }, { day: 2, level: "Apply", focus: "Draw body, label parts, write functions" }] },
  { id: "5-1.2", en: "Revision", unit: 1, pages: "4-5", days: 1, type: "phonics" as const,
    vocabulary: ["revise", "sounds", "words", "sentences", "read", "write"],
    structures: ["Read and match.", "Complete the sentence."],
    competencies: ["Revises Grade 4 English skills", "Reads familiar words at sight"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Revise sounds, words, reading from Grade 4" }] },
  { id: "5-1.3", en: "Be a Good Listener", unit: 1, pages: "6-8", days: 2, type: "conversation" as const,
    vocabulary: ["listen", "attention", "understand", "response", "speaker", "quiet", "respect", "wait"],
    structures: ["A good listener ___.", "When someone is speaking, I should ___."],
    competencies: ["Demonstrates listening skills", "Responds appropriately to speakers"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn rules of good listening" }, { day: 2, level: "Apply", focus: "Practice listening exercises, respond to questions" }] },
  { id: "5-1.4", en: "Let's speak", unit: 1, pages: "9", days: 1, type: "conversation" as const,
    vocabulary: ["introduce", "greet", "welcome", "visitor", "guest"],
    structures: ["I would like to introduce ___.", "Welcome to our school."],
    competencies: ["Introduces people formally", "Welcomes guests"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Role-play introductions and welcoming" }] },
  { id: "5-1.5", en: "English Sounds", unit: 1, pages: "10-11", days: 2, type: "phonics" as const,
    vocabulary: ["silent letters", "kn", "wr", "mb", "gh", "ght"],
    structures: ["In the word ___, the letter ___ is silent."],
    competencies: ["Identifies silent letters in words", "Reads words with silent letters"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn kn (know), wr (write), mb (lamb)" }, { day: 2, level: "Apply", focus: "Learn gh (night), read words, sort by pattern" }] },
  { id: "5-1.6", en: "Nibble Nibble", unit: 1, pages: "12-13", days: 2, type: "poem" as const,
    vocabulary: ["nibble", "mouse", "house", "garden", "seeds", "leaves", "quiet", "little"],
    structures: ["Nibble nibble, little mouse.", "Who is nibbling at my ___?"],
    competencies: ["Recites poem", "Identifies rhyming words", "Enjoys rhythm"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, find rhyming words" }, { day: 2, level: "Apply", focus: "Create new verses, substitute animals" }] },
  { id: "5-1.7", en: "A Nation United", unit: 1, pages: "14-17", days: 3, type: "story" as const,
    vocabulary: ["nation", "united", "freedom", "flag", "anthem", "republic", "democracy", "citizen", "rights", "duties"],
    structures: ["Our nation is ___.", "As citizens, we should ___."],
    competencies: ["Reads about national unity", "Discusses citizenship", "Writes about duties"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read passage, learn about national symbols" }, { day: 2, level: "Understand", focus: "Discuss rights and duties of citizens" }, { day: 3, level: "Apply", focus: "Write 5 sentences about being a good citizen" }] },
  // Unit 2
  { id: "5-2.1", en: "What's in the Bag?", unit: 2, pages: "18-19", days: 2, type: "conversation" as const,
    vocabulary: ["bag", "contents", "guess", "describe", "touch", "feel", "shape", "heavy", "light"],
    structures: ["What's in the bag?", "It feels ___.", "I think it is a ___."],
    competencies: ["Describes objects by touch", "Guesses using clues"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Play guessing game, describe objects" }, { day: 2, level: "Apply", focus: "Describe unknown objects, expand vocabulary" }] },
  { id: "5-2.2", en: "Tenses", unit: 2, pages: "20-22", days: 3, type: "conversation" as const,
    vocabulary: ["tense", "present", "past", "future", "yesterday", "today", "tomorrow", "will", "was", "is"],
    structures: ["Yesterday I ___.", "Today I am ___.", "Tomorrow I will ___."],
    competencies: ["Uses simple present, past, future tense", "Identifies tense in sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn simple present tense rules" }, { day: 2, level: "Understand", focus: "Learn simple past tense, regular/irregular verbs" }, { day: 3, level: "Apply", focus: "Learn future tense with will, write in all three tenses" }] },
  { id: "5-2.3", en: "English Sounds 2", unit: 2, pages: "23-24", days: 2, type: "phonics" as const,
    vocabulary: ["prefix", "suffix", "un", "re", "ful", "less", "ness", "ly"],
    structures: ["Add ___ to make a new word.", "Un + happy = unhappy."],
    competencies: ["Identifies prefixes and suffixes", "Forms new words using affixes"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn prefixes: un-, re-, dis-" }, { day: 2, level: "Apply", focus: "Learn suffixes: -ful, -less, -ly, build words" }] },
  { id: "5-2.4", en: "I am Lucky", unit: 2, pages: "25-27", days: 2, type: "story" as const,
    vocabulary: ["lucky", "grateful", "thankful", "appreciate", "family", "home", "food", "school", "friends"],
    structures: ["I am lucky because ___.", "I am grateful for ___."],
    competencies: ["Reads reflective passage", "Expresses gratitude", "Writes about self"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read passage about being lucky" }, { day: 2, level: "Apply", focus: "Write about what makes you lucky, share" }] },
  { id: "5-2.5", en: "Our Environment", unit: 2, pages: "28-30", days: 2, type: "picture-talk" as const,
    vocabulary: ["environment", "nature", "pollution", "clean", "recycle", "plant", "save", "water", "air", "earth"],
    structures: ["We should ___ to protect the environment.", "Pollution is caused by ___."],
    competencies: ["Discusses environmental issues", "Suggests solutions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn environment vocabulary, identify problems" }, { day: 2, level: "Apply", focus: "Write 5 ways to protect environment" }] },
  { id: "5-2.6", en: "Project 1", unit: 2, pages: "31", days: 1, type: "conversation" as const,
    vocabulary: ["project", "chart", "poster", "environment"],
    structures: ["Our project is about ___."],
    competencies: ["Creates environmental awareness project"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Make poster about saving the environment" }] },
  // Unit 3
  { id: "5-3.1", en: "Proverbs", unit: 3, pages: "32-33", days: 2, type: "conversation" as const,
    vocabulary: ["proverb", "saying", "wisdom", "meaning", "moral", "lesson"],
    structures: ["The proverb means ___.", "For example, ___."],
    competencies: ["Understands common proverbs", "Explains meanings with examples"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn 5-6 proverbs with meanings" }, { day: 2, level: "Apply", focus: "Match proverbs to situations, use in sentences" }] },
  { id: "5-3.2", en: "Gender", unit: 3, pages: "34-35", days: 2, type: "conversation" as const,
    vocabulary: ["gender", "masculine", "feminine", "boy", "girl", "man", "woman", "king", "queen", "actor", "actress"],
    structures: ["The masculine of ___ is ___.", "___ is the feminine of ___."],
    competencies: ["Identifies masculine and feminine forms", "Uses gender pairs correctly"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn masculine-feminine word pairs" }, { day: 2, level: "Apply", focus: "Fill in gender pairs, use in sentences" }] },
  { id: "5-3.3", en: "English Sounds 3", unit: 3, pages: "36-37", days: 2, type: "phonics" as const,
    vocabulary: ["compound", "words", "foot+ball", "rain+bow", "sun+flower", "class+room"],
    structures: ["___ + ___ = ___.", "A compound word is ___."],
    competencies: ["Identifies compound words", "Forms compound words"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn compound words from two simple words" }, { day: 2, level: "Apply", focus: "Form compound words, use in sentences" }] },
  { id: "5-3.4", en: "Don't Give Up", unit: 3, pages: "38-40", days: 2, type: "story" as const,
    vocabulary: ["give up", "try", "again", "difficult", "practise", "achieve", "success", "persevere", "dream"],
    structures: ["Don't give up!", "If you try again, you can ___."],
    competencies: ["Reads motivational story", "Discusses perseverance"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story about not giving up" }, { day: 2, level: "Apply", focus: "Share personal experience of trying again, write" }] },
  { id: "5-3.5", en: "Dialogue Writing", unit: 3, pages: "41-42", days: 2, type: "conversation" as const,
    vocabulary: ["dialogue", "conversation", "speaker", "quotation marks", "said", "asked", "replied"],
    structures: ["'___,' said ___.", "___ asked, '___?'"],
    competencies: ["Writes dialogues", "Uses quotation marks", "Creates conversations"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn dialogue format with quotation marks" }, { day: 2, level: "Apply", focus: "Write dialogue between two characters" }] },
  { id: "5-3.6", en: "Information Transfer", unit: 3, pages: "43-44", days: 2, type: "picture-talk" as const,
    vocabulary: ["table", "chart", "graph", "data", "information", "compare", "most", "least"],
    structures: ["According to the chart, ___.", "The most ___ is ___."],
    competencies: ["Reads tables and charts", "Transfers information to sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read data from table/chart" }, { day: 2, level: "Apply", focus: "Write sentences based on chart data" }] },
  // Unit 4
  { id: "5-4.1", en: "A Great Scientist", unit: 4, pages: "45-48", days: 3, type: "story" as const,
    vocabulary: ["scientist", "discover", "invention", "experiment", "curious", "research", "laboratory"],
    structures: ["The scientist discovered ___.", "He/She was famous for ___."],
    competencies: ["Reads biography", "Describes achievements", "Writes about role models"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read about the scientist, key facts" }, { day: 2, level: "Understand", focus: "Discuss importance of curiosity and discovery" }, { day: 3, level: "Apply", focus: "Write about a person you admire" }] },
  { id: "5-4.2", en: "Articles", unit: 4, pages: "49-50", days: 2, type: "conversation" as const,
    vocabulary: ["article", "a", "an", "the", "vowel", "consonant", "specific", "general"],
    structures: ["Use 'a' before ___.", "Use 'an' before ___.", "'The' is used when ___."],
    competencies: ["Uses a/an/the correctly", "Identifies article rules"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn rules for a, an, the" }, { day: 2, level: "Apply", focus: "Fill articles in passages, write own sentences" }] },
  { id: "5-4.3", en: "Prepositions", unit: 4, pages: "51-52", days: 2, type: "conversation" as const,
    vocabulary: ["preposition", "on", "in", "at", "to", "from", "by", "with", "for", "about"],
    structures: ["The book is ___ the table.", "She went ___ the market."],
    competencies: ["Uses prepositions correctly", "Identifies prepositions in sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn common prepositions with examples" }, { day: 2, level: "Apply", focus: "Fill prepositions in sentences, describe positions" }] },
  { id: "5-4.4", en: "Reading Comprehension", unit: 4, pages: "53-55", days: 2, type: "story" as const,
    vocabulary: ["passage", "comprehension", "infer", "conclude", "opinion", "fact"],
    structures: ["The passage suggests that ___.", "We can infer that ___."],
    competencies: ["Reads unseen passages", "Answers inferential questions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read passage, identify key facts" }, { day: 2, level: "Understand", focus: "Make inferences, distinguish fact from opinion" }] },
  { id: "5-4.5", en: "Notice / Message Writing", unit: 4, pages: "56-57", days: 2, type: "conversation" as const,
    vocabulary: ["notice", "message", "date", "subject", "attention", "important", "information"],
    structures: ["Notice: All students are requested to ___.", "Message: ___ called to say ___."],
    competencies: ["Writes notices", "Takes and writes messages"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn notice and message format" }, { day: 2, level: "Apply", focus: "Write a school notice and a phone message" }] },
  { id: "5-4.6", en: "Project 2", unit: 4, pages: "58", days: 1, type: "conversation" as const,
    vocabulary: ["project", "biography", "research"],
    structures: ["Our project is about ___."],
    competencies: ["Researches and presents biographical project"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Present project on a famous person" }] },
  // Unit 5
  { id: "5-5.1", en: "Conjunctions", unit: 5, pages: "59-60", days: 2, type: "conversation" as const,
    vocabulary: ["conjunction", "and", "but", "or", "because", "so", "although", "join", "connect"],
    structures: ["I like ___ and ___.", "She is tired but ___.", "He ran because ___."],
    competencies: ["Uses conjunctions to join sentences", "Identifies conjunctions"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn conjunctions: and, but, or, because, so" }, { day: 2, level: "Apply", focus: "Join sentences using conjunctions" }] },
  { id: "5-5.2", en: "Degrees of Comparison", unit: 5, pages: "61-63", days: 2, type: "conversation" as const,
    vocabulary: ["compare", "positive", "comparative", "superlative", "tall", "taller", "tallest", "good", "better", "best"],
    structures: ["___ is taller than ___.", "___ is the tallest of all."],
    competencies: ["Uses three degrees of comparison", "Compares objects and people"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn positive, comparative, superlative forms" }, { day: 2, level: "Apply", focus: "Compare classmates, objects, write sentences" }] },
  { id: "5-5.3", en: "The Enormous Turnip", unit: 5, pages: "64-67", days: 3, type: "story" as const,
    vocabulary: ["enormous", "turnip", "pull", "help", "grandfather", "grandmother", "dog", "cat", "mouse", "together"],
    structures: ["They pulled and pulled but ___.", "Then ___ came to help."],
    competencies: ["Reads cumulative story", "Sequences events", "Understands teamwork"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Read story, identify who helped" }, { day: 2, level: "Understand", focus: "Discuss moral: teamwork makes hard tasks easy" }, { day: 3, level: "Apply", focus: "Enact story, write summary" }] },
  { id: "5-5.4", en: "Paragraph Writing", unit: 5, pages: "68-69", days: 2, type: "conversation" as const,
    vocabulary: ["paragraph", "topic sentence", "supporting", "conclusion", "indent"],
    structures: ["The topic sentence is ___.", "In conclusion, ___."],
    competencies: ["Writes structured paragraphs", "Uses topic sentences"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn paragraph structure" }, { day: 2, level: "Apply", focus: "Write paragraph on My Best Friend or My Pet" }] },
  { id: "5-5.5", en: "Formal Letters", unit: 5, pages: "70-72", days: 2, type: "conversation" as const,
    vocabulary: ["formal", "letter", "sir", "madam", "application", "request", "faithfully", "subject"],
    structures: ["Respected Sir/Madam,", "I am writing to request ___.", "Yours faithfully, ___."],
    competencies: ["Writes formal/application letters", "Uses formal language"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn formal letter format" }, { day: 2, level: "Apply", focus: "Write application letter to principal" }] },
  // Unit 6
  { id: "5-6.1", en: "A Wonderful World", unit: 6, pages: "73-74", days: 2, type: "poem" as const,
    vocabulary: ["wonderful", "world", "beautiful", "nature", "sky", "ocean", "mountains", "rivers", "peace"],
    structures: ["What a wonderful world!", "I see ___ and I think to myself ___."],
    competencies: ["Recites poem about nature", "Describes the world around"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn poem, appreciate nature imagery" }, { day: 2, level: "Apply", focus: "Write about what makes the world wonderful" }] },
  { id: "5-6.2", en: "Idioms and Phrases", unit: 6, pages: "75-76", days: 2, type: "conversation" as const,
    vocabulary: ["idiom", "phrase", "meaning", "raining cats and dogs", "break a leg", "piece of cake"],
    structures: ["The idiom ___ means ___.", "It's a piece of cake means ___."],
    competencies: ["Understands common idioms", "Uses idioms in context"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn 6 common English idioms with meanings" }, { day: 2, level: "Apply", focus: "Match idioms to meanings, use in sentences" }] },
  { id: "5-6.3", en: "My Favourite Book", unit: 6, pages: "77-79", days: 2, type: "conversation" as const,
    vocabulary: ["book", "author", "character", "favourite", "story", "recommend", "interesting"],
    structures: ["My favourite book is ___.", "I like it because ___.", "I recommend ___ because ___."],
    competencies: ["Talks about books", "Writes book reviews", "Recommends books"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Describe a favourite book: title, author, story" }, { day: 2, level: "Apply", focus: "Write short book review, present to class" }] },
  { id: "5-6.4", en: "Story Writing", unit: 6, pages: "80-82", days: 3, type: "story" as const,
    vocabulary: ["story", "plot", "character", "setting", "climax", "resolution", "moral"],
    structures: ["Once upon a time, ___.", "The problem was ___.", "In the end, ___."],
    competencies: ["Plans and writes stories", "Uses story elements"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Learn story elements: character, setting, plot" }, { day: 2, level: "Apply", focus: "Plan story outline with beginning, middle, end" }, { day: 3, level: "Apply", focus: "Write complete story, share with class" }] },
  { id: "5-6.5", en: "Essay Writing", unit: 6, pages: "83-85", days: 2, type: "conversation" as const,
    vocabulary: ["essay", "introduction", "body", "conclusion", "opinion", "argument"],
    structures: ["In my opinion, ___.", "There are many reasons why ___."],
    competencies: ["Writes essays on familiar topics", "Organises ideas logically"],
    bloomsProgression: [{ day: 1, level: "Remember", focus: "Review essay format with example" }, { day: 2, level: "Apply", focus: "Write essay on My Village/City or My Hobby" }] },
  { id: "5-6.6", en: "Project 3", unit: 6, pages: "86", days: 1, type: "conversation" as const,
    vocabulary: ["project", "final", "year", "learning", "growth"],
    structures: ["This year I learned ___."],
    competencies: ["Reflects on year's learning", "Presents final project"],
    bloomsProgression: [{ day: 1, level: "Apply", focus: "Present final project, reflect on learning" }] },
];

export const grade5EnglishL2AssessmentGroups: Record<string, { name: string; lessons: string[]; focus: string }> = {
  "5-A1": { name: "Unit 1: Body & Nation", lessons: ["5-1.1", "5-1.2", "5-1.3", "5-1.4", "5-1.5", "5-1.6", "5-1.7"], focus: "Body poem, revision, listening, silent letters, Nibble Nibble, national unity" },
  "5-A2": { name: "Unit 2: Tenses & Environment", lessons: ["5-2.1", "5-2.2", "5-2.3", "5-2.4", "5-2.5", "5-2.6"], focus: "Guessing game, tenses, prefixes/suffixes, gratitude, environment" },
  "5-A3": { name: "Unit 3: Grammar & Values", lessons: ["5-3.1", "5-3.2", "5-3.3", "5-3.4", "5-3.5", "5-3.6"], focus: "Proverbs, gender, compound words, perseverance, dialogues, charts" },
  "5-A4": { name: "Unit 4: Science & Writing", lessons: ["5-4.1", "5-4.2", "5-4.3", "5-4.4", "5-4.5", "5-4.6"], focus: "Scientist biography, articles, prepositions, comprehension, notices" },
  "5-A5": { name: "Unit 5: Advanced Grammar & Story", lessons: ["5-5.1", "5-5.2", "5-5.3", "5-5.4", "5-5.5"], focus: "Conjunctions, comparison, Enormous Turnip, paragraphs, formal letters" },
  "5-A6": { name: "Unit 6: Expression & Creativity", lessons: ["5-6.1", "5-6.2", "5-6.3", "5-6.4", "5-6.5", "5-6.6"], focus: "Wonderful World poem, idioms, book reviews, story writing, essays" },
};
